### ISSUE TITLE
Problems with installing module

### ISSUE THREAD

**Issue by kkocel** [joeferner/node-java#146]
During installation I'm having the following error.

```
C:\Users\me\Desktop\myproject> npm install java
-
> java@0.4.2 install C:\Users\me\Desktop\myproject\node_modules\java
> node-gyp rebuild


C:\Users\me\Desktop\myproject\node_modules\java>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
VCBUILD : error Message:  [C:\Users\me\Desktop\myproject\node_modules\java\build\binding.sln]
VCBUILD : System error : -2147154687. [C:\Users\me\Desktop\myproject\node_modules\java\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\me\Desktop\myproject\node_modules\java
gyp ERR! node -v v0.10.30
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
npm ERR! java@0.4.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.4.2 install script.
npm ERR! This is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "java"
npm ERR! cwd C:\Users\me\Desktop\myproject
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\me\Desktop\myproject\npm-debug.log
npm ERR! not ok code 0
```

**Comment by pradeepvemulakonda** [comment]
I have the same problem too.It works on Ubuntu, but I get the same error when installing on Windows 8.1.Anyone has an answer for this?

**Comment by jimlloyd** [comment]
@jgoodall I believe I've seen reports of similar problems on ubuntu (with other npm packages) because node is installed as `nodejs` (or maybe `node.js`). If scripts assume that node can be run as `node` the scripts fail on unbuntu. The easy workaround is to install a symlink so that node can be run as `node`. Does this fix your problem?

@viliauvinen It's possible you have a similar problem, if node has to be run as `node.exe`. It's been ages since I've done anything with Windows (and I like it that way!) but I did a little Googling just now and came across something that might be helpful: http://www.2ality.com/2011/12/nodejs-shell-scripting.html#comment-388370938

**Comment by lordazzi** [comment]
Same error here, and node run as 'node' in shell, not as node.exe or anything else... ):
