### ISSUE TITLE
Error: /node_modules/java/build/Release/nodejavabridge_bindings.node: failed to map segment from shared object: Operation not permitted

### ISSUE THREAD

**Issue by ans-4175** [joeferner/node-java#184]
I am kind of experimental trying node-java. I wrote my code (index.js) like this
var http = require('http');
var java = require("java");

var server = http.createServer(function(req, res) {
  res.writeHead(200);
  res.end('Hello Http');
});

var TestClass = java.import("com.njava.Test");
var result = TestClass.addNumbersSync(1, 2);
console.log(result);

server.listen(3030);

I have put my class package same level with index.js
But when I test node, I got this error:
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /mnt/Windows/xampp/htdocs/nodejs/njava/node_modules/java/build/Release/nodejavabridge_bindings.node: failed to map segment from shared object: Operation not permitted
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/mnt/Windows/xampp/htdocs/nodejs/njava/node_modules/java/lib/nodeJavaBridge.js:7:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Am i missing something ?

**Comment by marcelboettcher** [comment]
Have you solved it? What was the problem? Thx!
