### ISSUE TITLE
Urgent! Cannot install on Windows 8.1 x64 (with x64 node, x64 Microsoft Visual C++ 2012, x64 java)

### ISSUE THREAD

**Issue by thetiby** [joeferner/node-java#190]
I have no idea why this is happening, and looking at previously closed issues, I have all requirements in place:
![image](https://cloud.githubusercontent.com/assets/2418978/5788826/04c9c0d2-9e56-11e4-9f8e-c6fb3ad0f7bf.png)
![image](https://cloud.githubusercontent.com/assets/2418978/5788869/aeeeb11a-9e58-11e4-86af-22f8201261f4.png)

I tried running `npm install --msvs_version=2012 java` and I have this same error:
```
C:\Users\Tiberiu>npm install --msvs_version=2012 java
-
> java@0.4.4 install C:\Users\Tiberiu\node_modules\java
> node-gyp rebuild


C:\Users\Tiberiu\node_modules\java>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js"
rebuild
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:1011:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:802:34)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Tiberiu\node_modules\java
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! java@0.4.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.4.4 install script.
npm ERR! This is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--msvs_version=2012" "java"
npm ERR! cwd C:\Users\Tiberiu
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

Please help!

**Comment by joeferner** [comment]
You might want to look at this thread https://github.com/TooTallNate/node-gyp/issues/277

**Comment by thetiby** [comment]
@joeferner Thank you!
I look at that thread before but failed to notice the `c:\Python27\python.exe` in the `%PYTHON%` var - as you saw in my ss, I had only the python folder in this variable. (`c:\Python27\`)

The install ran successfully after I made that change!
