### ISSUE TITLE
node-gyp build fails: cannot find bindings

### ISSUE THREAD

**Issue by PaulBGD** [joeferner/node-java#193]
I'm not new to node-gyp, and my environment is setup for it. However, when I run node-gyp it fails with the message

    No such file or directory [C:\Users\paul_000\Documents\Coding\Workspaces\Project\node_modules\java\build\nodejavabridge_bindings.vcxproj]

Everything else looks to be right.

**Comment by gyandeeps** [comment]
I am getting kind of a similar error.

```.sh
$ npm install
\
> java@0.4.6 install c:\Users\GS025879\Documents\webstrom\ccl-runner\node_modules\java
> node-gyp rebuild


c:\Users\GS025879\Documents\webstrom\ccl-runner\node_modules\java>node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
child_process: customFds option is deprecated, use stdio instead.
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
c:\Users\GS025879\Documents\webstrom\ccl-runner\node_modules\java\build\nodejavabridge_bindings.vcxproj(18,3): error MSB4019: The imported project "c:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\GS025879\Documents\webstrom\ccl-runner\node_modules\java
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

```

**Comment by gyandeeps** [comment]
I am not sure if my error is along the same line or not.
https://github.com/joeferner/node-java/issues/196
