### ISSUE TITLE
nodejavabridge_bindings.node: undefined symbol: node_module_register

### ISSUE THREAD

**Issue by clns** [joeferner/node-java#240]
This happens at `require('java')` on **Ubuntu 14.04.3 LTS** running **node.js v0.12.7** in a docker container. The installation of node-java runs fine though.

```
Error: .../node_modules/java/build/Release/nodejavabridge_bindings.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (.../node_modules/java/lib/nodeJavaBridge.js:10:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by clns** [comment]
This is actually related to GitLab's custom hooks, [gitlab-shell#25](https://gitlab.com/gitlab-org/gitlab-shell/issues/25).
