### ISSUE TITLE
Error: Could not create class com.nearinfinity.nodeJava.MyClass

### ISSUE THREAD

**Issue by juniorkid** [joeferner/node-java#244]
I have an error 

/home/bright/Desktop/Web/NodeJS/node_modules/java/lib/nodeJavaBridge.js:205
  var clazz = java.findClassSync(name); // TODO: change to Class.forName when 
                   ^
Error: Could not create class com.nearinfinity.nodeJava.MyClass
java.lang.UnsupportedClassVersionError: com/nearinfinity/nodeJava/MyClass : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)

    at Error (native)
    at Java.java.import (/home/bright/Desktop/Web/NodeJS/node_modules/java/lib/nodeJavaBridge.js:205:20)
    at Object.<anonymous> (/home/bright/Desktop/Web/NodeJS/node_modules/java/examples/mixJavaAndNode/runMyClass.js:6:26)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

this program is in example in node-java

how can i fix it ? 

thank you

**Comment by jimlloyd** [comment]
> Unsupported major.minor version 51.0

It looks like you are trying to use classes compiles for Java 7 with a JRE that doesn't support Java 7. Are you still running Java 6?

**Comment by juniorkid** [comment]
Thank you for comment . I can fix it.
But today have one problem when i use command
node runMyClass.js (this file in example) 
result is

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x013213b5, pid=3835, tid=10589904
#
# JRE version: 6.0_33-b33
# Java VM: OpenJDK Server VM (23.25-b01 mixed mode, sharing linux-x86 )
# Derivative: IcedTea6 1.13.5
# Distribution: Ubuntu 10.04.1 LTS, package 6b33-1.13.5-1ubuntu0.10.04
# Problematic frame:
# V  [libjvm.so+0x40d3b5]  get_method_id(JNIEnv_*, _jclass*, char const*, char const*, bool, Thread*)+0x75
#
# Core dump written. Default location: /home/bright/Desktop/web/node_modules/java/examples/mixJavaAndNode/core or core.3835
#
# An error report file with more information is saved as:
# /home/bright/Desktop/web/node_modules/java/examples/mixJavaAndNode/hs_err_pid3835.log
#
# If you would like to submit a bug report, please include
# instructions how to reproduce the bug and visit:
#   https://bugs.launchpad.net/ubuntu/+source/openjdk-6/
#
Aborted (core dumped)

how to fix it ??
Thank you for suggestion.
Sorry for bad english.

**Comment by juniorkid** [comment]
i use opnejdk6 in my ubuntu 10.04

**Comment by juniorkid** [comment]
i use openjdk 6 in ubuntu 10.04

**Comment by jimlloyd** [comment]
Sorry, we dropped support for openjdk 6 back in January with this commit: https://github.com/joeferner/node-java/commit/20d6e0436d7f58fbc046c6f427c01d63b411d5fd

If you must use openjdk 6, I suggest you try backing up to java@0.4.4.

**Comment by juniorkid** [comment]
Thank you for suggestion.
How i can backing up to java@0.4.4. . I am a beginner in ubuntu .

**Comment by jimlloyd** [comment]
In your package.json, where you list your dependency on java, try this:

    "dependencies": {
      ...
      "java": "=0.4.4",
      ...
    },

After changing the package.json, run `npm install` again.

**Comment by juniorkid** [comment]
thank you i will try it

**Comment by juniorkid** [comment]
Thank you for your suggestion. It's done.

**Comment by jimlloyd** [comment]
Glad to hear it worked.
