### ISSUE TITLE
nodejavabridge_bindings.node: undefined symbol: node_module_register

### ISSUE THREAD

**Issue by masalinas** [joeferner/node-java#263]
My SO is:
  - Ubuntu 12.04
  - Oracle Java 1.7.0_72

when install node-java with npm install java install correctly. But when execute your simple example:

var java = require("java");
java.classpath.push("commons-lang3-3.1.jar");
java.classpath.push("commons-io.jar");

var list = java.newInstanceSync("java.util.ArrayList");

java.newInstance("java.util.ArrayList", function(err, list) {
  list.addSync("item1");
  list.addSync("item2");
});

var ArrayList = java.import('java.util.ArrayList');
var list = new ArrayList();
list.addSync('item1');

I obtain this error:

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/miguel/Sources/myNodeJava/node_modules/java/build/Release/nodejavabridge_bindings.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/miguel/Sources/myNodeJava/node_modules/java/lib/nodeJavaBridge.js:10:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

What is the problem ??? 

Regards.

**Comment by harmic** [comment]
I saw this error when I had inadvertently selected the wrong node version before running my program.

I had built node-java with node 0.12 selected, and then when I ran my program 0.10 was selected. That threw this error.
