### ISSUE TITLE
Failed at the java@0.6.0 install script 'node-gyp rebuild' 

### ISSUE THREAD

**Issue by arathim** [joeferner/node-java#275]
I have node v4.1.1 and when I run  npm install java I get this error 

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-504.8.1.el6.x86_64
gyp ERR! command "/root/.nvm/versions/node/v4.1.1/bin/node" "/root/.nvm/versions/node/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/nodejs/sg-admin/56422f6ec93894cc2998ca43/node_modules/sg-jmx-api/node_modules/java
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 2.6.32-504.8.1.el6.x86_64
npm ERR! argv "/root/.nvm/versions/node/v4.1.1/bin/node" "/root/.nvm/versions/node/v4.1.1/bin/npm" "install" "java"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! java@0.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1

I checked lots of  forums, it says java0.6 works for nodev4. But it is not working. Please tell me what I should do.

**Comment by jsdevel** [comment]
it's a sad state of affairs now with the rate of breaking changes in node :/

**Comment by sachinrodge** [comment]
Even I am getting the same error

**Comment by VikramBPurohit** [comment]
I am also having the same issue. Does anyone figure it out on how to resolve?

**Comment by lhulet** [comment]
Same here :/

**Comment by jibin-tj** [comment]
Same here
npm ERR! Linux 2.6.32-573.18.1.el6.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! java@0.6.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.6.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the java package,
npm ERR! not with npm itself.

**Comment by galen-elfert** [comment]
I'm having the same issue. First when trying to install ts-java, then when I tried to compile manually with node-gyp. Here is a more complete trace:

```
../src/java.cpp:1258:14: error: expected type-specifier
../src/java.cpp:1258:14: error: expected ‘;’
../src/java.cpp:1265:12: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::TypeError(const char*)’:
../node_modules/nan/nan.h:643:3: warning: control reaches end of non-void function [-Wreturn-type]
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::Error(const char*)’:
../node_modules/nan/nan.h:639:3: warning: control reaches end of non-void function [-Wreturn-type]
make: *** [Release/obj.target/nodejavabridge_bindings/src/java.o] Error 1
make: Leaving directory `/home/gelfert/src/node-java/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/node-v4.4.0-linux-x64/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-97-generic
gyp ERR! command "/opt/node-v4.4.0-linux-x64/bin/node" "/usr/bin/node-gyp" "configure" "build"
gyp ERR! cwd /home/gelfert/src/node-java
gyp ERR! node -v v4.4.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

```
