### ISSUE TITLE
Problems during installation

### ISSUE THREAD

**Issue by erobwen** [joeferner/node-java#280]
I try to install node-java but get the following message: 

`C:\forum\node_modules\java>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\forum\node_modules\java\build\nodejavabridge_bindings.vcxproj(18,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path i
n the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\forum\node_modules\java
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! java@0.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.6.0 install script.
npm ERR! This is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "java"
npm ERR! cwd C:\forum
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

C:\forum>`

**Comment by erobwen** [comment]
A step by step guide of how to install this module would be great, (with as much detail as possible). I have now installed Visual Studio, Python and Java, but there are still some problems. Right now I get

![image](https://cloud.githubusercontent.com/assets/7721859/11286346/d3a4f840-8f14-11e5-9c06-0b0e486b4733.png)

I have tried following suggestions from this link: http://stackoverflow.com/questions/16092169/why-does-msbuild-look-in-c-for-microsoft-cpp-default-props-instead-of-c-progr . But it seems that the win registry looks different on my machine.

**Comment by tobilg** [comment]
We're also facing problems with the installation on Win 7 64bit with multiple machines. Windows SDKs etc. are all installed.

**Comment by erobwen** [comment]
I finally solved it, using this solution (the simple solution on top of the page.)

http://blog.jimdhughes.com/2015/04/09/perils-with-node-gyp-and-windows-development/

Now I only have a warning about types, but it seems to install without error! 

![image](https://cloud.githubusercontent.com/assets/7721859/11302959/7278a260-8fa0-11e5-9d5e-a7137bbf3ee1.png)

Next step is trying to use the Neo4J API through the node-java interface. My goal is to increase performance since cypher is pretty slow when interfacing to Neo4J. (but that is not directly related to node-java)

**Comment by erobwen** [comment]
Btw, I had to update node.js to latest stable version in order for it to work.

**Comment by ganna-shmatova** [comment]
unfortunately the link with the solution is down. Says 502 bad gateway @erobwen 

Not quite sure if our issues are exact. I seem to be getting compilation issues (2nd machine too! everything freshly installed on this one). Related ticket in a sub-module I opened: https://github.com/CraZySacX/node-jdbc/issues/72

**Comment by ganna-shmatova** [comment]
Link works now, I think @erobwen was refering to `npm install -g --msvs_version=2015 node-gyp rebuild`. Unfortunately, while this rebuilds node-gyp fine installing java still gives me issues about node-gyp.

![image](https://cloud.githubusercontent.com/assets/7226694/11631209/f1b556dc-9cce-11e5-9435-c584bfe36b02.png)

**Comment by garrylachman** [comment]
same issue on Centos

**Comment by tobilg** [comment]
@erobwen I exactly followed http://blog.jimdhughes.com/2015/04/09/perils-with-node-gyp-and-windows-development/ but it's still not working. I suspect if because of the previously installed MS C++ packages, but I'm not sure of I can deinstall everything except MS Visual Studio 2015, because other programs might depend on these specific versions.
