### ISSUE TITLE
Error: libjvm.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by J0NNYZER0** [joeferner/node-java#306]
This happens when I install the jdk on heroku and load up the node-jdbc plugin which depends on this plugin. Full error is this:

Error: libjvm.so: cannot open shared object file: No such file or directory
remote:     at Error (native)
remote:     at Object.Module._extensions..node (module.js:440:18)
remote:     at Module.load (module.js:357:32)
remote:     at Function.Module._load (module.js:314:12)
remote:     at Module.require (module.js:367:17)
remote:     at require (internal/module.js:16:19)
remote:     at Object.<anonymous> (/app/node_modules/java/lib/nodeJavaBridge.js:21:16)
remote:     at Module._compile (module.js:413:34)
remote:     at Object.Module._extensions..js (module.js:422:10)
remote:     at Module.load (module.js:357:32)

**Comment by J0NNYZER0** [comment]
I posted this issue with a link to this page on stackoverflow as well
http://stackoverflow.com/questions/36191073/node-java-error-libjvm-so-cannot-open-shared-object-file-no-such-file-or-dire

**Comment by J0NNYZER0** [comment]
I figured it out and it's nothing to do with anything in joe's code. My badd

**Comment by melvinmmw** [comment]
@J0NNYZER0  i have the same error. can i know what did you do?

**Comment by jude-liu** [comment]
@J0NNYZER0  How can you solve this problem?

**Comment by tejaslodaya** [comment]
If someone is coming here now, Please try the approach below:

Steps:
1. Find your R location. It will be stored in `rsession-ld-library-path` in `rserver.conf` file. Or just by doing `which R`. The location usually is `/usr/lib64/R/lib` or `/usr/lib64/microsoft-r/3.3/lib64/R/lib`
2. Find the `libjvm.so` file which is usually in the `usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server` path depending on which jre you're using. Check in $JAVA_HOME environment.
3. Create a symlink using `ln -s`
`sudo ln -s /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so /usr/lib64/microsoft-r/3.3/lib64/R/lib/libjvm.so`
4. Restart R server

**Comment by pi-kei** [comment]
> I figured it out and it's nothing to do with anything in joe's code. My badd

@J0NNYZER0 What did you do? How did you solve it?

**Comment by pi-kei** [comment]
I figured it out.
1. Find where `libjvm.so` is located. `/app/.jdk/jre/lib/amd64/server` in my case.
2. Add it to `LD_LIBRARY_PATH` env var. I'm adding this in starting script.

**Comment by pnahtanoj** [comment]
I'm seeing this problem as well.  Locally on OSX, everything is working great.  When I move to ubuntu, I'm seeing the 'libjvm.so: cannot open shared object file' error.  I've tried setting the follow env variables as well:

export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64
export LD_LIBRARY_PATH=/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server 

But no luck.  All suggestions appreciated.

This is not a Heroku project.

**Comment by joeferner** [comment]
node Java is not tested with openjdk.
