### ISSUE TITLE
Error in java@0.6.1 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by projsaha** [joeferner/node-java#320]
Hello,

I am attempting to install jdbc module which has a dependency on node-java. The install fails with the node-java module - error stack is shown below. Looking forward to some assistance on this.
I am using node v4.2.2.

build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/scratch/node/node-v4.2.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.8.13-44.1.1.el6uek.x86_64
gyp ERR! command "/scratch/node/node-v4.2.2-linux-x64/bin/node" "/scratch/node/node-v4.2.2-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /scratch/workingDFML2/dataflowml/dfml-dev/apps/cloud-service/src/main/webapp/node_modules/java
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok 
npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN dfml@0.0.0 No description
npm WARN dfml@0.0.0 No repository field.
npm WARN dfml@0.0.0 No license field.
npm ERR! Linux 3.8.13-44.1.1.el6uek.x86_64
npm ERR! argv "/scratch/node/node-v4.2.2-linux-x64/bin/node" "/scratch/node/node-v4.2.2-linux-x64/bin/npm" "install" "jdbc"
npm ERR! node v4.2.2
npm ERR! npm  v3.8.0
npm ERR! code ELIFECYCLE

npm ERR! java@0.6.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the java@0.6.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs java
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /scratch/workingDFML2/dataflowml/dfml-dev/apps/cloud-service/src/main/webapp/npm-debug.log

**Comment by lxw0109** [comment]
Got the same Error Message. Can anybody help?

**Comment by lxw0109** [comment]
@projsaha I tried [this](https://github.com/nodejs/node-gyp/issues/809)

"*I had similar issues on Ubuntu 14.04, after trying everything here I finally solved it by running:
`sudo apt-get install build-essential`*"

And it works now. I Hope it helps.

**Comment by DeChrish** [comment]
any suggession for rhel ?

**Comment by uthaman** [comment]
@DeChrish did you find any solution for the C++11 compiler required error?

**Comment by DeChrish** [comment]
i have installed the correct compiler to resolve this issue

**Comment by uthaman** [comment]
@DeChrish culd you tell me which version of RHEL and C++ compiler fixed the issue. I have RHEL 6.8 (Santiago) and gcc , g++ 4.4.7 20120313

**Comment by DeChrish** [comment]
@uthaman : https://gist.github.com/stephenturner/e3bc5cfacc2dc67eca8b
