### ISSUE TITLE
Errors while invoking static method defined in java files(Could not invoke the static method)

### ISSUE THREAD

**Issue by lxw0109** [joeferner/node-java#325]
I defined a static method named `sayHelloStatic` in `Hello.java` as follows:
```Java
...
public static String sayHelloStatic(String str){
    return "lxw: Hello in sayHelloStatic()";
}
...
```
and in `main.js`, I want to call this static method `sayHelloStatic` like this: 
```JavaScript
var HelloClass = java.import('Hello');
var returnValStatic = java.callStaticMethodSync("Hello", "sayHelloStatic");
```
but I got the following error message:</br>
```Bash
App threw an error when running [Error: Could not find method "sayHelloStatic()" on class "class Hello". No methods with that name.]
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Could not find method "sayHelloStatic()" on class "class Hello". No methods with that name.
    at Error (native)
    at Object.<anonymous> (/home/lxw/IT/program/github/electronDemo/main.js:99:28)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at loadApplicationPackage (/usr/lib/node_modules/electron-prebuilt/dist/resources/default_app.asar/main.js:253:23)
    at Object.<anonymous> (/usr/lib/node_modules/electron-prebuilt/dist/resources/default_app.asar/main.js:293:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```
Besides, while call this static method `sayHelloStatic` like this:
```JavaScript
var HelloClass = java.import('Hello');
HelloClass.sayHelloStaticSync();
```
I got a similar error message as follows:</br>
```Bash
App threw an error when running [TypeError: HelloClass.sayHelloStaticSync is not a function]
```
I have also tried to call the non-static method using `callMethodSync()`, it works well.</br>
While calling the static method, it does not work.</br>
I would appreciate your help.</br>

**Comment by lxw0109** [comment]
Sorry, I made a mistake.
After modifying the `Hello.java` file, I did not compile it manually(`javac Hello.java`). So the `main.js` file always uses the old `Hello.class`.
