### ISSUE TITLE
 The specified module could not be found

### ISSUE THREAD

**Issue by jingjingwang** [joeferner/node-java#33]
Hi,

I was using windows xp 32bit. First, when I tried to "npm install java", I got several warnings:

C:\Program Files\Microsoft Visual Studio 10.0\VC\include\xlocale(323): warning
C4530: C++ exception handler used, but unwind semantics are not enabled. Specif
y /EHsc [xxxxxx\node_modules\java\build\nodejavabridge_bindings
.vcxproj]
C:\Program Files\Microsoft Visual Studio 10.0\VC\include\xlocale(323): warning
C4530: C++ exception handler used, but unwind semantics are not enabled. Specif
y /EHsc [xxxxxx\node_modules\java\build\nodejavabridge_bindings
.vcxproj]
C:\Documents and Settings\lenovo.node-gyp\0.8.15\deps\v8\include\v8.h(183): wa
rning C4506: no definition for inline function 'v8::Persistent<T> v8::Persisten
t<T>::New(v8::Handle<T>)' [xxxxxx\node_modules\java\build\nodej
avabridge_bindings.vcxproj]
          with
          [
              T=v8::Object
          ]
  nodeJavaBridge.cpp
  java.cpp
......

but without errors. 

So I then tried to launch my application by: "node client.js"

and got:

module.js:485
  process.dlopen(filename, module.exports);
          ^
Error: The specified module could not be found.
xxxxxx\node_modules\java\build\Release\nodejavabridge_bindings.n
ode
    at Object.Module._extensions..node (module.js:485:11)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (xxxxxx\node_modules\java\lib\nodeJava
Bridge.js:6:16)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

however I checked the path xxxxxx\node_modules\java\build\Release\nodejavabridge_bindings.node, and it was there.

I feel it might related to issue #29, so I tried the method in the comment, still had the same result.

The same things works well on both Mac and Linux.

Could anyone point me a solution? Thanks :)

**Comment by gazeldx** [comment]
Follow http://stackoverflow.com/questions/11718813/error-running-a-nodejs-server-on-a-mac-no-suitable-image-found

$ sudo rm -rf node_modules/
$ npm install

**Comment by souravprakashjena** [comment]
@joeferner  which path we have to change ???Is it **JAVA_HOME** path ??

**Comment by souravprakashjena** [comment]
@jingjingwang can u please tell  me how to fix this issue??

**Comment by antoinepairet** [comment]
@souravprakashjena What issue to you face? Are you having trouble installing node-java and using it? With recent versions of node-java, the path is automatically added at runtime based on a path that was generated at build time.

See postinstall script and `jvm_dll_path.json` file: https://github.com/joeferner/node-java/blob/master/postInstall.js#L22-L30

The path is appended at runtime: https://github.com/joeferner/node-java/blob/master/lib/nodeJavaBridge.js#L3

If you are having trouble, try removing your node_modules folder and reinstall:
`rm -rf node_modules`
`npm install`

**Comment by souravprakashjena** [comment]
@antoinepairet i am getting below error

D:\xyzFolder>node nodeServer
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\D:\xyzFolder\node_modules\java\build\Release\nodejavabridge_bindings.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\xyzFolder\node_modules\java\lib\nodeJavaBridge.js:21
:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

 
**Node Version-6.9.1

Windows Version- win 7(64-bit)**

**Comment by kitzler-walli** [comment]
Is there any way to fix this? I have one Win7Ent(x64) where it works without any issues and another Win7Pro (x64) where every execution leads to:

> module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^
> Error: The specified module could not be found.
\\?\C:\nodejs\wltpsync\node_modules\java\build\Release\nodejavabridge_bindings.node
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\nodejs\wltpsync\node_modules\java\lib\nodeJavaBridge.js:21:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

Node Version: 8.1.4
Npm Version: 5.0.3

I tried Java version 7u80, 8u151, 9u...

No combination works - I'm running out of ideas as of why it works on one machine and not on the other.

**Comment by vik-yar** [comment]
Thanks a lot!
