### ISSUE TITLE
Error happens when "bindings = require(binaryPath);" on windows 7 x86_32

### ISSUE THREAD

**Issue by haichao625** [joeferner/node-java#338]
Hi, 

I'm using node-java to support my features, and the node module compiling process is ok,
but when I tried to run my commands in vscode, below error happens on line "var bindings = require(binaryPath);" nodeJavaBridge.js.

Active the “TizenSDKTeam.tizenappdev” failed: The specified module could not be found.
\\?\c:\Users\guogg.SCRC\Desktop\jiangzong\tizenappdev\node_modules\java\build\Release\nodejavabridge_bindings.node。
Activating extension `TizenSDKTeam.tizenappdev` failed: The specified module could not be found.
\\?\c:\Users\guogg.SCRC\Desktop\jiangzong\tizenappdev\node_modules\java\build\Release\nodejavabridge_bindings.node
Here is the error stack: Error: The specified module could not be found.
\\?\c:\Users\guogg.SCRC\Desktop\jiangzong\tizenappdev\node_modules\java\build\Release\nodejavabridge_bindings.node
at Error (native)
at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
at Object.Module._extensions..node (module.js:440:18)
at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Function.M.N.n._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:17:18321)
at Module.require (module.js:367:17)
at require (internal/module.js:16:19)
at Object.<anonymous> (c:\Users\guogg.SCRC\Desktop\jiangzong\tizenappdev\node_modules\java\lib\nodeJavaBridge.js:22:18)

How can i fix it? Thanks.

**Comment by haichao625** [comment]
nodejavabridge_bindings.node has been generated sucessfully without any error

C:\Users\jianghc\Desktop\tizenappdev\node_modules>npm install java
npm WARN package.json tizenappdev@0.0.1 No repository field.
npm WARN package.json tizenappdev@0.0.1 No license field.
|
> java@0.7.2 install C:\Users\jianghc\Desktop\tizenappdev\node_modules\java
> node-gyp rebuild


C:\Users\jianghc\Desktop\tizenappdev\node_modules\java>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js"
 rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  java.cpp
  javaObject.cpp
  javaScope.cpp
  methodCallBaton.cpp
  nodeJavaBridge.cpp
  utils.cpp
..\src\utils.cpp(499): warning C4244: '=' : conversion from 'jchar' to 'char', possible loss of data [C:\Users\jianghc\Desktop\tizenappdev\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\utils.cpp(616): warning C4244: '=' : conversion from 'jchar' to 'char', possible loss of data [C:\Users\jianghc\Desktop\tizenappdev\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  win_delay_load_hook.c
     Creating library C:\Users\jianghc\Desktop\tizenappdev\node_modules\java\build\Release\nodejavabridge_bindings.lib and object C:\Users\jianghc\Desktop\tizenappdev\node_modules\java\build\Release\
  nodejavabridge_bindings.exp
  Generating code
  Finished generating code
  nodejavabridge_bindings.vcxproj -> C:\Users\jianghc\Desktop\tizenappdev\node_modules\java\build\Release\\nodejavabridge_bindings.node

> java@0.7.2 postinstall C:\Users\jianghc\Desktop\tizenappdev\node_modules\java
> node postInstall.js

npm WARN unmet dependency C:\Users\jianghc\Desktop\tizenappdev\node_modules\vscode requires glob@'^5.0.15' but will load
npm WARN unmet dependency C:\Users\jianghc\Desktop\tizenappdev\node_modules\glob,
npm WARN unmet dependency which is version 7.0.5
java@0.7.2 java
├── glob@7.0.3
├── nan@2.3.2
├── find-java-home@0.1.2 (which@1.0.9)
