### ISSUE TITLE
import Scala object

### ISSUE THREAD

**Issue by artola** [joeferner/node-java#341]
trying:
`var x = java.import('com.xxx.utils.UrlHelper');`

I am dealing with the following situation: importing Scala classes works fine, e.g.:

UrlHelper.scala
`package com.xxx.utils
import java.net.URL
class UrlHelper {
  def resolveUrl(urlString: String): UrlResolverResult = {
    ...
  }
}`

BUT when "object" is used does not work.
UrlHelper.scala
`package com.xxx.utils
import java.net.URL
object UrlHelper {
  def resolveUrl(urlString: String): UrlResolverResult = {
    ...
  }
}`

result:
/node_modules/java/lib/nodeJavaBridge.js:227   var clazz = java.findClassSync(name); // TODO: change to Class.forName when classloader issue is resolved.

Error: Could not create class com.xxx.utils.UrlHelper
java.lang.NoClassDefFoundError: com/xxx/utils/UrlHelper
Caused by: java.lang.ClassNotFoundException: com.xxx.utils.UrlHelper
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by artola** [comment]
I found that adding `$` at the end the import works, eg:
`var x = java.import('com.xxx.utils.UrlHelper$');`
