### ISSUE TITLE
java@0.7.2 install  -  node-gyp rebuild

### ISSUE THREAD

**Issue by KellyWillard** [joeferner/node-java#342]
g:\stsProject\swagger-view>npm i --save jdbc

> java@0.7.2 install g:\stsProject\swagger-view\node_modules\java
> node-gyp rebuild

g:\stsProject\swagger-view\node_modules\java>if not defined npm_config_node_gyp (node "C:\Users\DBA\AppData\Roaming\npm\node_modules\npm\bin
\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
g:\stsProject\swagger-view\node_modules\java\build\binding.sln : error MSB3411: Could not load the Visual C++ component "VCBuild.exe".
If the component is not installed, either 1) install the Microsoft Windows SDK for Windows Server 2008 and .NET Framework 3.5, or 2)
install Microsoft Visual Studio 2008.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v3.5\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\DBA\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "G:\\usr\\nodejs\\node.exe" "C:\\Users\\DBA\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd g:\stsProject\swagger-view\node_modules\java
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
swagger-view@ g:\stsProject\swagger-view
`-- (empty)

npm WARN swagger-view@ No description
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "G:\\usr\\nodejs\\node.exe" "C:\\Users\\DBA\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "--save" "jdbc"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! java@0.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.7.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs java
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     g:\stsProject\swagger-view\npm-debug.log
npm ERR! code 1

**Comment by jaivikqedata** [comment]
I am getting the same error

**Comment by Bikasa** [comment]
I am also getting the same error.This issue is coming as my system doesn't have JDK installed.I just install JDK and set the environment variable path for my system.Now doing 'npm install' working fine for me.

To install JDK and setting environment variable path follow the below link.
[https://www3.ntu.edu.sg/home/ehchua/programming/howto/JDK_Howto.html](url)
