### ISSUE TITLE
java.import not working with packaged electron app using asar

### ISSUE THREAD

**Issue by antoinepairet** [joeferner/node-java#352]
With a package app using an asar archive, `java.import` does not work. 
The following line of code will throw an error:

`var DateTime = java.import('org.joda.time.DateTime');`

````
Error: Could not create class org.joda.time.DateTime
java.lang.NoClassDefFoundError: org/joda/time/DateTime
Caused by: java.lang.ClassNotFoundException: org.joda.time.DateTime
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

    at Error (native)
    at Java.java.import (...)
````

Only the packaged version of the app fails. 
Launching the unpackaged electron app will work fine.

The app was packaged with the following command:
````
electron-packager ./app --out=dist --asar.unpack='**/node_modules/java/**/*'
````

I guess the function `java.import` needs to be adapted in order to work with packaged electron apps.

Let me know if I can provide more information.

regards

**Comment by antoinepairet** [comment]
Also reported on the asar repo: https://github.com/electron/asar/issues/88

**Comment by antoinepairet** [comment]
When `java-node` is used together with `asar` archives, make sure to

- Unpack all java-related files

- Make sure unpacked files are used

I will make a PR to update the README and add a `Electron and asar archive` section
