### ISSUE TITLE
Trying to rebuild with electron - V8 header errors

### ISSUE THREAD

**Issue by TimMurnaghan** [joeferner/node-java#359]
Platform Windows 7
node-java 0.7.2
electron 1.4.2

# using --dist-url to get electron versions of headers
node-gyp rebuild --target=1.4.2 --arch=x64 --dist-url=https://atom.io/download/atom-shell

..\src\utils.cpp(647): error C2039: 'SetHiddenValue': is not a member of 'v8::N
umberObject' [C:\excel-converter\node_modules\java\build\nodejavabridge_binding
s.vcxproj]

Clearly incompatible - the code's looking for something that's not there.
Two choices:
- node-java shouldn't be looking
- electron's V8 should have it

but which is it?

**Comment by vrmerlin** [comment]
I too am having problems with electron and node-java. See #344 . It feels like the node-java package needs an upgrade to a new version of V8.  I tried Node 4.5.0, 6.2.0, and 6.7.0, and all have show-stopping problems. Is a fix to this problem under development?

**Comment by joeferner** [comment]
I'm hoping an upgrade to node-nan will fix the issue. I'm not sure when I'll get around to fixing though.

**Comment by vrmerlin** [comment]
Do you anticipated days, or many months...? We were hoping to base a very large project on Electron and Java (to legacy jar files), and at the moment, we are completely blocked from moving forward.

**Comment by joeferner** [comment]
I update nan (d071069c0adb04c307f15b2d614e50db0e72fafb) and added node 6 to travis build (c6daaa213a58a669c7b14ac3894d90adfa08f9b9). Can you test your electron build with master?

**Comment by vrmerlin** [comment]
Thanks for taking a look! Unfortunately, it's still not working. I'm getting the same compiler error in the Java bridge code during the electron-rebuild:

```
../src/javaObject.cpp:350:18: error: ‘class v8::Object’ has no member named ‘SetHiddenValue’
   javaObjectObj->SetHiddenValue(Nan::New<v8::String>(V8_HIDDEN_MARKER_JAVA_OBJECT).ToLocalChecked(), Nan::New<v8::Boolean>(true));
                  ^
make: *** [Release/obj.target/nodejavabridge_bindings/src/javaObject.o] Error 1
```

Some warnings coming up as well.

This happens when I use Node 6.2.0 or 6.7.0.

Here is my package.json:

```
{
  "name": "nava_node_test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "electron": "^1.4.2",
    "java": "git+https://github.com/joeferner/node-java.git"
  },
  "devDependencies": {
    "electron-rebuild": "^1.2.1"
  }
}
```

And here is my build script:

```
#!/bin/bash
npm install 
./node_modules/.bin/electron-rebuild
```

**Comment by enlight** [comment]
@joeferner You can fix this similarly to how I've fixed it in `node-inspector` (see https://github.com/node-inspector/v8-profiler/pull/96). NAN probably won't get updated until Node upgrades to V8 5.2 or later.

**Comment by vrmerlin** [comment]
@enlight Thanks, glad you've got a solution for this! @joeferner , can you put the fix in?

**Comment by vrmerlin** [comment]
@joeferner  can you provide a timeframe on when you can make this fix?

**Comment by joeferner** [comment]
Give it another try. Thanks @enlight for the tip.

https://github.com/joeferner/node-java/commit/b6c0577382e16633b802934ed052bcac90aa195d

**Comment by vrmerlin** [comment]
Thanks for looking at it, @joeferner . I did the exact same steps as above, but now get this error from the electron-rebuild:

```
gyp ERR! clean error 
gyp ERR! stack Error: ENOTEMPTY: directory not empty, rmdir 'build/Release'
gyp ERR! stack     at Error (native)
gyp ERR! System Linux 3.10.0-327.36.1.el7.x86_64
gyp ERR! command "/opt/node-v6.7.0-linux-x64/bin/node" "/u/fisher23/javaNodeTest/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /u/fisher23/javaNodeTest/node_modules/nslog
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```
Ideas? I tried removing my node_modules directory entirely and running again (twice), and it produces the same error.

John

**Comment by joeferner** [comment]
can you go into `node_modules/java` directory and manually remove the `build` directory and run install from there

**Comment by vrmerlin** [comment]
It's interesting -- it looks like the "electron-rebuild" is giving the error I said above, but it appears that the "fix" is actually still taking place. That is, after the error, I can then run "node_modules/electron/dist/electron index.js", and it runs as expected.   That's great, but is there a way to make my build.sh script work, without getting an error message?

**Comment by Cheonsoon** [comment]
@joeferner hi, issue were fixed by applying b6c0577 on electron 1.4.3, thanks~

**Comment by gcstang** [comment]
@vrmerlin when I try this line(node_modules/electron/dist/electron index.js) I'm getting Uncaught Exception: Error: Module version mismatch. Expected 50, got 48.  

Maybe this is unrelated but trying to use your instructions so far to get setup.

**Comment by vrmerlin** [comment]
@gcstang  did you run the electron-rebuild command? you need to do that after npm install, but before you run the code.  More details are here: https://github.com/electron/electron-rebuild

**Comment by vrmerlin** [comment]
@joeferner  do you know how i can avoid the "directory not empty, rmdir 'build/Release'" error during the electron-rebuild step, without a bunch of manual steps?

**Comment by gcstang** [comment]
@vrmerlin thank you that was it, now to see how to get java output to show in the window.

**Comment by gcstang** [comment]
@vrmerlin thank you very much for your help, I used this to get some output to a index.html file for now and it worked.  https://github.com/joeferner/node-java/blob/master/testIntegration/webkit/index.html

**Comment by vrmerlin** [comment]
@joeferner  -- can you help with the problem I described above (avoiding the "directory not empty" error), that's breaking the electron-rebuild step when recompiling the node-java bridge?

**Comment by vrmerlin** [comment]
@joeferner  The code fix you created in the master branch,  [b6c0577](https://github.com/joeferner/node-java/commit/b6c0577382e16633b802934ed052bcac90aa195d), worked -- will you be cutting a new software version that I can point to? Any thoughts on the "directory not empty" issue?

**Comment by Cheonsoon** [comment]
@vrmerlin while, b6c0577 seems buggy at some point. While I intergate it with newest electron, and frequently comes out Memory Error..About 2-3times per day

**Comment by vrmerlin** [comment]
@joeferner   Is there a path forward here? Are you maintaining node-java still?

**Comment by vrmerlin** [comment]
@joeferner  Would you please help here? Can you at least cut the version that includes the fixes you made?

**Comment by joeferner** [comment]
published 0.8.0

**Comment by Bhuvn12** [comment]
E:\Learn\test>npm i node-any-jdbc
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=4.12.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=4.11.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> java@0.7.2 install E:\Learn\test\node_modules\java
> node-gyp rebuild


E:\Learn\test\node_modules\java>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  java.cpp
  javaObject.cpp
  javaScope.cpp
  methodCallBaton.cpp
  nodeJavaBridge.cpp
e:\learn\test\node_modules\nan\nan_maybe_43_inl.h(220): warning C4996: 'v8::Array::CloneElementAt': was declared deprecated (compiling source file ..\
src\java.cpp) [E:\Learn\test\node_modules\java\build\nodejavabridge_bindings.vcxproj]
e:\learn\test\node_modules\nan\nan_maybe_43_inl.h(220): warning C4996: 'v8::Array::CloneElementAt': was declared deprecated (compiling source file ..\
src\methodCallBaton.cpp)c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(3516): note: see declaration of 'v8::Array::CloneElementAt' (compiling sourc
e file ..\src\java.cpp) [E:\Learn\test\node_modules\java\build\nodejavabridge_bindings.vcxproj]

  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(3516): note: see declaration of 'v8::Array::CloneElementAt' (compiling source file ..\src\methodCa
  llBaton.cpp)
e:\learn\test\node_modules\nan\nan_maybe_43_inl.h(220): warning C4996: 'v8::Array::CloneElementAt': was declared deprecated (compiling source file ..\
src\javaObject.cpp) [E:\Learn\test\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(3516): note: see declaration of 'v8::Array::CloneElementAt' (compiling source file ..\src\javaObje
  ct.cpp)
e:\learn\test\node_modules\nan\nan_implementation_12_inl.h(40): warning C4996: 'v8::BooleanObject::New': was declared deprecated (compiling source fil
e ..\src\methodCallBaton.cpp)e:\learn\test\node_modules\nan\nan_implementation_12_inl.h(40): warning C4996: 'v8::BooleanObject::New': was declared dep
recated (compiling source file ..\src\java.cpp) [E:\Learn\test\node_modules\java\build\nodejavabridge_bindings.vcxproj]

  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(4845): note: see declaration of 'v8::BooleanObject::New' (compiling source file ..\src\methodCallB
  aton.cpp)c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(4845): note: see declaration of 'v8::BooleanObject::New' (compiling source file ..\src\ja
  va.cpp)

e:\learn\test\node_modules\nan\nan_implementation_12_inl.h(40): warning C4996: 'v8::BooleanObject::New': was declared deprecated (compiling source fil
e ..\src\javaObject.cpp) [E:\Learn\test\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(4845): note: see declaration of 'v8::BooleanObject::New' (compiling source file ..\src\javaObject.
  cpp)
e:\learn\test\node_modules\nan\nan.h(2017): warning C4996: 'v8::Object::SetAccessor': was declared deprecated (compiling source file ..\src\methodCall
Baton.cpp)e:\learn\test\node_modules\nan\nan.h(2017): warning C4996: 'v8::Object::SetAccessor': was declared deprecated (compiling source file ..\src\
java.cpp) [E:\Learn\test\node_modules\java\build\nodejavabridge_bindings.vcxproj]

  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(3186): note: see declaration of 'v8::Object::SetAccessor' (compiling source file ..\src\methodCall
  Baton.cpp)c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(3186): note: see declaration of 'v8::Object::SetAccessor' (compiling source file ..\src\
  java.cpp)

e:\learn\test\node_modules\nan\nan.h(2017): warning C4996: 'v8::Object::SetAccessor': was declared deprecated (compiling source file ..\src\javaObject
.cpp) [E:\Learn\test\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(3186): note: see declaration of 'v8::Object::SetAccessor' (compiling source file ..\src\javaObject
  .cpp)
e:\learn\test\node_modules\java\src\javaobject.cpp(117): error C2039: 'SetHiddenValue': is not a member of 'v8::Object' [E:\Learn\test\node_modules\ja
va\build\nodejavabridge_bindings.vcxproj]
  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(3054): note: see declaration of 'v8::Object'
e:\learn\test\node_modules\java\src\javaobject.cpp(116): warning C4996: 'v8::Function::NewInstance': was declared deprecated [E:\Learn\test\node_modul
es\java\build\nodejavabridge_bindings.vcxproj]
e:\learn\test\node_modules\java\src\java.cpp(897): warning C4996: 'v8::Value::ToNumber': was declared deprecatedc:\users\bhuvn\.node-gyp\8.11.3\includ
e\node\v8.h(3851): note: see declaration of 'v8::Function::NewInstance' [E:\Learn\test\node_modules\java\build\nodejavabridge_bindings.vcxproj]

  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(9760): note: see declaration of 'v8::Value::ToNumber'
e:\learn\test\node_modules\java\src\javaobject.cpp(350): error C2039: 'SetHiddenValue': is not a member of 'v8::Object'e:\learn\test\node_modules\java
\src\java.cpp(927): warning C4996: 'v8::Value::ToNumber': was declared deprecated [E:\Learn\test\node_modules\java\build\nodejavabridge_bindings.vcxpr
oj]

  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(3054): note: see declaration of 'v8::Object'c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(9760
  ): note: see declaration of 'v8::Value::ToNumber'

e:\learn\test\node_modules\java\src\javaobject.cpp(349): warning C4996: 'v8::Function::NewInstance': was declared deprecatede:\learn\test\node_modules
\java\src\java.cpp(956): warning C4996: 'v8::Value::ToNumber': was declared deprecated [E:\Learn\test\node_modules\java\build\nodejavabridge_bindings.
vcxproj]

  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(3851): note: see declaration of 'v8::Function::NewInstance'c:\users\bhuvn\.node-gyp\8.11.3\include
  \node\v8.h(9760): note: see declaration of 'v8::Value::ToNumber'

e:\learn\test\node_modules\java\src\java.cpp(983): warning C4996: 'v8::Value::ToNumber': was declared deprecated [E:\Learn\test\node_modules\java\buil
d\nodejavabridge_bindings.vcxproj]
  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(9760): note: see declaration of 'v8::Value::ToNumber'
e:\learn\test\node_modules\java\src\java.cpp(1019): warning C4996: 'v8::Value::ToNumber': was declared deprecated [E:\Learn\test\node_modules\java\bui
ld\nodejavabridge_bindings.vcxproj]
  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(9760): note: see declaration of 'v8::Value::ToNumber'
e:\learn\test\node_modules\java\src\java.cpp(1044): warning C4996: 'v8::Value::ToNumber': was declared deprecated [E:\Learn\test\node_modules\java\bui
ld\nodejavabridge_bindings.vcxproj]
  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(9760): note: see declaration of 'v8::Value::ToNumber'
  utils.cpp
e:\learn\test\node_modules\java\src\java.cpp(1263): warning C4996: 'v8::TryCatch::TryCatch': was declared deprecated [E:\Learn\test\node_modules\java\
build\nodejavabridge_bindings.vcxproj]
  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(8313): note: see declaration of 'v8::TryCatch::TryCatch'
  win_delay_load_hook.cc
e:\learn\test\node_modules\nan\nan_maybe_43_inl.h(220): warning C4996: 'v8::Array::CloneElementAt': was declared deprecated (compiling source file ..\
src\nodeJavaBridge.cpp) [E:\Learn\test\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(3516): note: see declaration of 'v8::Array::CloneElementAt' (compiling source file ..\src\nodeJava
  Bridge.cpp)
e:\learn\test\node_modules\nan\nan_implementation_12_inl.h(40): warning C4996: 'v8::BooleanObject::New': was declared deprecated (compiling source fil
e ..\src\nodeJavaBridge.cpp) [E:\Learn\test\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(4845): note: see declaration of 'v8::BooleanObject::New' (compiling source file ..\src\nodeJavaBri
  dge.cpp)
e:\learn\test\node_modules\nan\nan.h(2017): warning C4996: 'v8::Object::SetAccessor': was declared deprecated (compiling source file ..\src\nodeJavaBr
idge.cpp) [E:\Learn\test\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(3186): note: see declaration of 'v8::Object::SetAccessor' (compiling source file ..\src\nodeJavaBr
  idge.cpp)
e:\learn\test\node_modules\nan\nan_maybe_43_inl.h(220): warning C4996: 'v8::Array::CloneElementAt': was declared deprecated (compiling source file ..\
src\utils.cpp) [E:\Learn\test\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(3516): note: see declaration of 'v8::Array::CloneElementAt' (compiling source file ..\src\utils.cp
  p)
e:\learn\test\node_modules\nan\nan_implementation_12_inl.h(40): warning C4996: 'v8::BooleanObject::New': was declared deprecated (compiling source fil
e ..\src\utils.cpp) [E:\Learn\test\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(4845): note: see declaration of 'v8::BooleanObject::New' (compiling source file ..\src\utils.cpp)
e:\learn\test\node_modules\nan\nan.h(2017): warning C4996: 'v8::Object::SetAccessor': was declared deprecated (compiling source file ..\src\utils.cpp)
 [E:\Learn\test\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(3186): note: see declaration of 'v8::Object::SetAccessor' (compiling source file ..\src\utils.cpp)
e:\learn\test\node_modules\java\src\utils.cpp(296): error C2039: 'GetHiddenValue': is not a member of 'v8::Object' [E:\Learn\test\node_modules\java\bu
ild\nodejavabridge_bindings.vcxproj]
  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(3054): note: see declaration of 'v8::Object'
e:\learn\test\node_modules\java\src\utils.cpp(370): error C2039: 'GetHiddenValue': is not a member of 'v8::Object' [E:\Learn\test\node_modules\java\bu
ild\nodejavabridge_bindings.vcxproj]
  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(3054): note: see declaration of 'v8::Object'
e:\learn\test\node_modules\java\src\utils.cpp(375): error C2039: 'GetHiddenValue': is not a member of 'v8::Object' [E:\Learn\test\node_modules\java\bu
ild\nodejavabridge_bindings.vcxproj]
  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(3054): note: see declaration of 'v8::Object'
e:\learn\test\node_modules\java\src\utils.cpp(347): warning C4996: 'v8::Value::ToInt32': was declared deprecated [E:\Learn\test\node_modules\java\buil
d\nodejavabridge_bindings.vcxproj]
  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(9796): note: see declaration of 'v8::Value::ToInt32'
e:\learn\test\node_modules\java\src\utils.cpp(354): warning C4996: 'v8::Value::ToNumber': was declared deprecated [E:\Learn\test\node_modules\java\bui
ld\nodejavabridge_bindings.vcxproj]
  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(9760): note: see declaration of 'v8::Value::ToNumber'
e:\learn\test\node_modules\java\src\utils.cpp(499): warning C4244: '=': conversion from 'jchar' to 'char', possible loss of data [E:\Learn\test\node_m
odules\java\build\nodejavabridge_bindings.vcxproj]
e:\learn\test\node_modules\java\src\utils.cpp(616): warning C4244: '=': conversion from 'jchar' to 'char', possible loss of data [E:\Learn\test\node_m
odules\java\build\nodejavabridge_bindings.vcxproj]
e:\learn\test\node_modules\java\src\utils.cpp(647): error C2039: 'SetHiddenValue': is not a member of 'v8::NumberObject' [E:\Learn\test\node_modules\j
ava\build\nodejavabridge_bindings.vcxproj]
  c:\users\bhuvn\.node-gyp\8.11.3\include\node\v8.h(4826): note: see declaration of 'v8::NumberObject'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Learn\test\node_modules\java
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'E:\Learn\test\package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java@0.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.7.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bhuvn\AppData\Roaming\npm-cache\_logs\2018-10-14T14_07_45_910Z-debug.log

how can i solve this 
node v8.11.3
npm v5.6.0

package.json

{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "dependencies": {
    "nan": "^2.11.1"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
