### ISSUE TITLE
mismatch when installing Node.js app

### ISSUE THREAD

**Issue by jcald1** [joeferner/node-java#365]
I have a Node.js application that uses the node "java" dependency.  I did an "npm install" on it, but when I run it, I get the following Module version mismatch error.  I tried doing an "npm cache clean" and removing the node_modules directory.  I did that several times.  I'm running Java 1.7 on Ubuntu.

    Error: Module version mismatch. Expected 14, got 47.
        at Error (native)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/myapp/java/lib/nodeJavaBridge.js:21:16)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
    "myapp.out" 70L, 3125C      

package.json:

      "dependencies": {
        "java": "0.7.2",

**Comment by joeferner** [comment]
Can you try `npm rebuild` http://stackoverflow.com/a/26371450

The other possibility i's that node-java is building with one version of node and ruining with a different
