### ISSUE TITLE
Error: v8::Isolate::GCEpilogueCallback callback

### ISSUE THREAD

**Issue by loretoparisi** [joeferner/node-java#368]
I get this error on

```
$ npm -v
3.10.3
$ node -v
v6.3.0
```

and macOS Sierra 10.12.11

Stacktrace:

```
npm install stanford-classifier --save
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> java@0.6.0 install /my-app/node_modules/java
> node-gyp rebuild

2016-11-22 18:37:31.966 xcodebuild[68190:16069135] [MT] PluginLoading: Required plug-in compatibility UUID DA4FDFD8-C509-4D8B-8B55-84A7B66AE701 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
../node_modules/nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/nodejavabridge_bindings/src/java.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /my-app/node_modules/java
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "stanford-classifier" "--save"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! java@0.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the java@0.6.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs java
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.
```

**Comment by loretoparisi** [comment]
**[UPDATE]**

I report that moving back to:

```
$ node --version
v5.5.0
```

it works again.

**Comment by loretoparisi** [comment]
I'm running again in the same issue o a different machine

```
$ export JAVA_HOME=`/usr/libexec/java_home -v 1.6.0_65-b14-468, x86_64`
$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

v5.5.0
loretoparisi$ npm -v
3.3.12
loretoparisi$ npm install
```

I have also tried ad discussed here https://github.com/joeferner/node-java/issues/86

```
$ export JAVA_HOME=/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/
$ java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
```

that is pretty much what I have done above, but I get the same error

```
> node-gyp rebuild

  CXX(target) Release/obj.target/iconv/src/binding.o
  CC(target) Release/obj.target/iconv/deps/libiconv/lib/iconv.o
  SOLINK_MODULE(target) Release/iconv.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9

> ursa@0.9.4 install /Volumes/MacHDD2/Projects/MusiXmatch/musixmatch-intelligence-analysis-sdk/node_modules/ursa
> node-gyp rebuild

  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
  SOLINK_MODULE(target) Release/ursaNative.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9

> java@0.6.0 install /Volumes/MacHDD2/Projects/MusiXmatch/musixmatch-intelligence-analysis-sdk/node_modules/java
> node-gyp rebuild

  CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
In file included from ../src/java.cpp:1:
../src/java.h:7:10: fatal error: 'jni.h' file not found
#include <jni.h>
```

and

```
npm ERR! java@0.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the java@0.6.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

**Comment by loretoparisi** [comment]
We have `node 6.9.2` as LTS, this issues should be solved definitively!

**Comment by loretoparisi** [comment]
@joeferner any idea of what the `node` developer says about `nan` module support in `v8`?

**Comment by loretoparisi** [comment]
**[UPDATE]**

The problem was that for some reason, `npm` was installing `java 0.6.0` so that it didn't work with `JVMv8`. After changing the package.json with 

```
java:"latest`
```

It works!

**Comment by loretoparisi** [comment]
By the way even with `java@0.8.0` we have some errors

```
> java@0.8.0 install /musixmatch/node_modules/java
> node-gyp rebuild

make: Entering directory '/musixmatch/node_modules/java/build'
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
../src/java.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE Java::newByte(Nan::NAN_METHOD_ARGS_TYPE)':
../src/java.cpp:897:49: warning: 'v8::Local<v8::Number> v8::Value::ToNumber() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Number> val = info[0]->ToNumber();
                                                 ^
In file included from ../src/java.h:5:0,
                 from ../src/java.cpp:1:
/root/.node-gyp/6.9.2/include/node/v8.h:8166:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^
../src/java.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE Java::newShort(Nan::NAN_METHOD_ARGS_TYPE)':
../src/java.cpp:927:49: warning: 'v8::Local<v8::Number> v8::Value::ToNumber() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Number> val = info[0]->ToNumber();
                                                 ^
In file included from ../src/java.h:5:0,
                 from ../src/java.cpp:1:
/root/.node-gyp/6.9.2/include/node/v8.h:8166:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^
../src/java.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE Java::newLong(Nan::NAN_METHOD_ARGS_TYPE)':
../src/java.cpp:956:49: warning: 'v8::Local<v8::Number> v8::Value::ToNumber() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Number> val = info[0]->ToNumber();
                                                 ^
In file included from ../src/java.h:5:0,
                 from ../src/java.cpp:1:
/root/.node-gyp/6.9.2/include/node/v8.h:8166:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^
../src/java.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE Java::newChar(Nan::NAN_METHOD_ARGS_TYPE)':
../src/java.cpp:983:51: warning: 'v8::Local<v8::Number> v8::Value::ToNumber() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
     v8::Local<v8::Number> val = info[0]->ToNumber();
                                                   ^
In file included from ../src/java.h:5:0,
                 from ../src/java.cpp:1:
/root/.node-gyp/6.9.2/include/node/v8.h:8166:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^
../src/java.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE Java::newFloat(Nan::NAN_METHOD_ARGS_TYPE)':
../src/java.cpp:1019:49: warning: 'v8::Local<v8::Number> v8::Value::ToNumber() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Number> val = info[0]->ToNumber();
                                                 ^
In file included from ../src/java.h:5:0,
                 from ../src/java.cpp:1:
/root/.node-gyp/6.9.2/include/node/v8.h:8166:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^
../src/java.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE Java::newDouble(Nan::NAN_METHOD_ARGS_TYPE)':
../src/java.cpp:1044:49: warning: 'v8::Local<v8::Number> v8::Value::ToNumber() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Number> val = info[0]->ToNumber();
                                                 ^
In file included from ../src/java.h:5:0,
                 from ../src/java.cpp:1:
/root/.node-gyp/6.9.2/include/node/v8.h:8166:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^
../src/java.cpp: In function 'void EIO_AfterCallJs(uv_work_t*)':
../src/java.cpp:1263:16: warning: 'v8::TryCatch::TryCatch()' is deprecated: Use isolate version [-Wdeprecated-declarations]
   v8::TryCatch tryCatch;
                ^
In file included from /root/.node-gyp/6.9.2/include/node/v8.h:25:0,
                 from ../src/java.h:5,
                 from ../src/java.cpp:1:
/root/.node-gyp/6.9.2/include/node/v8.h:6771:40: note: declared here
   V8_DEPRECATED("Use isolate version", TryCatch());
                                        ^
/root/.node-gyp/6.9.2/include/node/v8config.h:333:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/javaObject.o
../src/javaObject.cpp: In static member function 'static v8::Local<v8::Object> JavaObject::New(Java*, jobject)':
../src/javaObject.cpp:116:59: warning: 'v8::Local<v8::Object> v8::Function::NewInstance() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Object> javaObjectObj = ctor->NewInstance();
                                                           ^
In file included from /root/.node-gyp/6.9.2/include/node/v8.h:25:0,
                 from ../src/javaObject.h:5,
                 from ../src/javaObject.cpp:1:
/root/.node-gyp/6.9.2/include/node/v8.h:3274:52: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                    ^
/root/.node-gyp/6.9.2/include/node/v8config.h:333:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
../src/javaObject.cpp: In static member function 'static v8::Local<v8::Object> JavaProxyObject::New(Java*, jobject, DynamicProxyData*)':
../src/javaObject.cpp:349:59: warning: 'v8::Local<v8::Object> v8::Function::NewInstance() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::Local<v8::Object> javaObjectObj = ctor->NewInstance();
                                                           ^
In file included from /root/.node-gyp/6.9.2/include/node/v8.h:25:0,
                 from ../src/javaObject.h:5,
                 from ../src/javaObject.cpp:1:
/root/.node-gyp/6.9.2/include/node/v8.h:3274:52: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                    ^
/root/.node-gyp/6.9.2/include/node/v8config.h:333:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/javaScope.o
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/methodCallBaton.o
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/nodeJavaBridge.o
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/utils.o
../src/utils.cpp: In function '_jobject* v8ToJava(JNIEnv*, v8::Local<v8::Value>)':
../src/utils.cpp:347:29: warning: 'v8::Local<v8::Int32> v8::Value::ToInt32() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
     jint val = arg->ToInt32()->Value();
                             ^
In file included from ../src/utils.h:6:0,
                 from ../src/utils.cpp:1:
/root/.node-gyp/6.9.2/include/node/v8.h:8202:14: note: declared here
 Local<Int32> Value::ToInt32() const {
              ^
../src/utils.cpp:354:33: warning: 'v8::Local<v8::Number> v8::Value::ToNumber() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
     jdouble val = arg->ToNumber()->Value();
                                 ^
In file included from ../src/utils.h:6:0,
                 from ../src/utils.cpp:1:
/root/.node-gyp/6.9.2/include/node/v8.h:8166:15: note: declared here
 Local<Number> Value::ToNumber() const {
               ^
../src/utils.cpp: In function 'v8::Local<v8::Value> GetHiddenValue(v8::Local<v8::Object>, v8::Local<v8::String>)':
../src/utils.cpp:969:38: warning: 'v8::Local<v8::Value> v8::Object::GetHiddenValue(v8::Local<v8::String>)' is deprecated: Use v8::Object::GetPrivate instead. [-Wdeprecated-declarations]
     return object->GetHiddenValue(key);
                                      ^
In file included from /root/.node-gyp/6.9.2/include/node/v8.h:25:0,
                 from ../src/utils.h:6,
                 from ../src/utils.cpp:1:
/root/.node-gyp/6.9.2/include/node/v8.h:2956:30: note: declared here
                 Local<Value> GetHiddenValue(Local<String> key));
                              ^
/root/.node-gyp/6.9.2/include/node/v8config.h:333:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
../src/utils.cpp: In function 'void SetHiddenValue(v8::NumberObject*, v8::Local<v8::String>, v8::Local<v8::Value>)':
../src/utils.cpp:973:38: warning: 'bool v8::Object::SetHiddenValue(v8::Local<v8::String>, v8::Local<v8::Value>)' is deprecated: Use v8::Object::SetPrivate instead. [-Wdeprecated-declarations]
     object->SetHiddenValue(key, value);
                                      ^
In file included from /root/.node-gyp/6.9.2/include/node/v8.h:25:0,
                 from ../src/utils.h:6,
                 from ../src/utils.cpp:1:
/root/.node-gyp/6.9.2/include/node/v8.h:2954:22: note: declared here
                 bool SetHiddenValue(Local<String> key, Local<Value> value));
                      ^
/root/.node-gyp/6.9.2/include/node/v8config.h:333:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
../src/utils.cpp: In function 'void SetHiddenValue(v8::Local<v8::Object>, v8::Local<v8::String>, v8::Local<v8::Value>)':
../src/utils.cpp:977:38: warning: 'bool v8::Object::SetHiddenValue(v8::Local<v8::String>, v8::Local<v8::Value>)' is deprecated: Use v8::Object::SetPrivate instead. [-Wdeprecated-declarations]
     object->SetHiddenValue(key, value);
                                      ^
In file included from /root/.node-gyp/6.9.2/include/node/v8.h:25:0,
                 from ../src/utils.h:6,
                 from ../src/utils.cpp:1:
/root/.node-gyp/6.9.2/include/node/v8.h:2954:22: note: declared here
                 bool SetHiddenValue(Local<String> key, Local<Value> value));
                      ^
/root/.node-gyp/6.9.2/include/node/v8config.h:333:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
  SOLINK_MODULE(target) Release/obj.target/nodejavabridge_bindings.node
  COPY Release/nodejavabridge_bindings.node
make: Leaving directory '/musixmatch/node_modules/java/build'
```
