### ISSUE TITLE
Install fails of java module ($ node install java) on windows-10  64 bit 

### ISSUE THREAD

**Issue by souravprakashjena** [joeferner/node-java#373]
> java@0.8.0 install E:\xyz\node_modules\java
> node-gyp rebuild

E:\xyz\node_modules\java>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  java.cpp
  javaObject.cpp
  javaScope.cpp
  methodCallBaton.cpp
C:\Program Files\Java\jdk1.8.0_91\include\jni.h(39): fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory (compiling source file ..\src\javaScope.cpp) [E:\xyz\node_modules\java\build\nodejavabridge_
bindings.vcxproj]
  nodeJavaBridge.cpp
C:\Users\souravprakash.j\.node-gyp\6.9.1\include\node\v8.h(18): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory (compiling source file ..\src\javaObject.cpp) [E:\xyz\node_modules\java\build\no
dejavabridge_bindings.vcxproj]
C:\Users\souravprakash.j\.node-gyp\6.9.1\include\node\v8.h(18): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory (compiling source file ..\src\java.cpp) [E:\xyz\node_modules\java\build\nodejava
bridge_bindings.vcxproj]
C:\Users\souravprakash.j\.node-gyp\6.9.1\include\node\v8.h(18): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory (compiling source file ..\src\methodCallBaton.cpp) [E:\xyz\node_modules\java\bui
ld\nodejavabridge_bindings.vcxproj]
  utils.cpp
  win_delay_load_hook.cc
C:\Users\souravprakash.j\.node-gyp\6.9.1\include\node\v8.h(18): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory (compiling source file ..\src\nodeJavaBridge.cpp) [E:\xyz\node_modules\java\buil
d\nodejavabridge_bindings.vcxproj]
C:\Users\souravprakash.j\.node-gyp\6.9.1\include\node\v8.h(18): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory (compiling source file ..\src\utils.cpp) [E:\xyz\node_modules\java\build\nodejav
abridge_bindings.vcxproj]
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(31): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\
win_delay_load_hook.cc) [E:\xyz\node_modules\java\build\nodejavabridge_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\xyz\node_modules\java
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'E:\xyz\package.json'
npm WARN xyzNo description
npm WARN xyzNo repository field.
npm WARN xyz No README data
npm WARN xyzNo license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "java"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! java@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.8.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs java
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\xyz\npm-debug.log

**Comment by stejsoftware** [comment]
You should try running this first:

```npm install --global --production windows-build-tools```

and make sure you are using the 32 bit version of the [JDK](https://edelivery.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-windows-i586.exe)

I had the same issue and it worked for me.

**Comment by vrmerlin** [comment]
@stejsoftware  -- I used the tool you suggested, and I can now download the electron-quick-start, add the java module to it, and when I run npm install, it appears to do the full build steps like I expect (the java cpp programs are compiled). But when I actually run the sample, I get this error:

``
App threw an error during load
Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\devel\electron-quick-start\node_modules\java\build\Release\nodejavabridge_bindings.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at C:\devel\electron-quick-start\node_modules\java\lib\nodeJavaBridge.js:21:16
    at Object.<anonymous> (C:\devel\electron-quick-start\node_modules\java\lib\nodeJavaBridge.js:316:2)
``

I can't seem to get rid of it. Did you figure out this part?

John

**Comment by coco-napky** [comment]
Any update on this? I managed to get up to this part and im getting this same error
