### ISSUE TITLE
v0.8.0: Error: Module version mismatch. Expected 47, got 48

### ISSUE THREAD

**Issue by jonvargas** [joeferner/node-java#377]
After setting up nvm, node and npm, and after running "npm install", I receive this error when running the app:

```
Uncaught Exception:
Error: Module version mismatch. Expected 47, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:159:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/jon/Projects/electron-pdfjs/node_modules/java/lib/nodeJavaBridge.js:21:16)
    at Module._compile (module.js:425:26)

```
 
Versions tested:

node: 6.9.4
npm: 3.10.10
java: 0.8.0

What could be wrong? I've already tried:

1. Deleting node_modules
2. npm rebuild
3. npm cache clean
4. rm -rfv ~/.npm

**Comment by joeferner** [comment]
Take a look at some of the suggestions here https://github.com/electron-userland/electron-builder/issues/453
