### ISSUE TITLE
Windows runtime error: "The specified module could not be found"

### ISSUE THREAD

**Issue by bleupen** [joeferner/node-java#385]
Hi!

I am trying to make this work on a fresh Windows 2016 Server with jdk 1.8.0_121. I have npm installed the latest versions of `windows-build-tools` and `java` on Node 6.10.1. Java compiles fine with no errors, however fails when required at runtime with:
```
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified module could not be found.
\\?\C:\Users\Administrator\test-java\node_modules\java\build\Release\nodejavabridge_bindings.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Administrator\test-java\node_modules\java\lib\nodeJavaBridge.js:21:16)
```

I have tried both 32 bit and 64 bit node/jdk combinations. Are folks able to make this library work with just `windows-build-tools` or do I need to install Visual Studio?

Thanks!

**Comment by tiagowippel** [comment]
hi, same here...

**Comment by tiagowippel** [comment]
@bleupen  Can you solve this?

**Comment by tiagowippel** [comment]
Just can solve that by installing Visual Studio Community 2017... maybe some dependence was missing...

**Comment by dasarindam** [comment]
Did you installed this after rebuilding your application ? or before rebuilding ?
TIA

**Comment by tiagowippel** [comment]
before "npm i node-java" ...
