### ISSUE TITLE
Error: Invalid call to accessor onJvmCreated

### ISSUE THREAD

**Issue by loretoparisi** [joeferner/node-java#392]
I get this error while creating instance of different Java objects, I'm not sure this is causing further issues since the objects seem to have been allocated.

Stacktrace:

```
    onJvmCreated: 
     Error: Invalid call to accessor onJvmCreated
         at Error (native)
         at formatProperty (util.js:770:17)
         at util.js:654:12
         at Array.map (native)
         at formatObject (util.js:653:15)
         at formatValue (util.js:592:16)
         at formatProperty (util.js:794:15)
         at formatArray (util.js:665:19)
         at formatValue (util.js:592:16)
         at inspect (util.js:186:10),
```

**Comment by hamzadahmani** [comment]
@loretoparisi fixed? I have the same issue
