### ISSUE TITLE
I could not install node-jasper in my system 

### ISSUE THREAD

**Issue by Dhayal** [joeferner/node-java#400]
Hi There,

When I was trying to install node-jasper in my system, I received below output error messages. Could someone please look into this issue asap? 

C:\Users\KLR PC\Desktop\test>npm install --save node-jasper

> java@0.7.2 install C:\Users\KLR PC\Desktop\test\node_modules\java
> node-gyp rebuild

C:\Users\KLR PC\Desktop\test\node_modules\java>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\KLR PC\Desktop\test\node_modules\java
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
C:\Users\KLR PC\Desktop\test
+-- async@0.9.2
+-- extend@1.3.0
`-- temp@0.8.3
  +-- os-tmpdir@1.0.2
  `-- rimraf@2.2.8

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\KLR PC\Desktop\test\package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "node-jasper"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! java@0.7.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.7.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs java
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\KLR PC\Desktop\test\npm-debug.log

C:\Users\KLR PC\Desktop\test>node-gyp rebuild
'node-gyp' is not recognized as an internal or external command,
operable program or batch file.

Thanks in Advance.

**Comment by grahams777** [comment]
I have the same problem
Installed java 7.2 same problem still
Java  1.8.0 also installed - should this be uninstalled?

Any guidance on how to fix the issue please?

**Comment by davisokoth** [comment]
@Dhayal 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

> 

>

**Comment by VanisreeThazhedamVeedu** [comment]
What was the solution to this? I am geting the same error
