### ISSUE TITLE
IBM i post install - missing /Release/nodejavabridge_bindings.node

### ISSUE THREAD

**Issue by krisbaehr** [joeferner/node-java#417]
I'm running into an issue running node-java on an IBM i. The Install appears to work, but I get a runtime error when executing the script, and have since noticed that the npm_modules/java/build/Release directory does not exist. This is working great on Windows 10, but now I need to deploy to the server. Any help would be greatly appreciated!

**Install Log:**

> npm install java --javahome=$JAVA_HOME
 [K [?25h            [27m [90m... [0m] / build:path-is-absolute:  [34;40mverb [0m  [35mlinkMans [0m path-is-absolute@1 [K
> java@0.9.0 install /home/someone/node/projects/remote_users/node_modules/java
> node-gyp rebuild

gmake: Entering directory `/home/someone/node/projects/remote_users/node_modules/java/build'
gmake: Nothing to be done for `all'.
gmake: Leaving directory `/home/someone/node/projects/remote_users/node_modules/java/build'
 [K [?25h7m                [27m [90m... [0m] / postinstall:concat-map:  [7msill [0m  [35mlifecycle [0m concat-map@0.0.1~ [K
> java@0.9.0 postinstall /home/someone/node/projects/remote_users/node_modules/java
> node postInstall.js

remote_users@0.0.0 /home/someone/node/projects/remote_users
`--  [40m [33mjava@0.9.0 [39m [49m
  +--  [40m [33masync@2.5.0 [39m [49m
  +--  [40m [33mfind-java-home@0.2.0 [39m [49m
  | +--  [40m [33mwhich@1.0.9 [39m [49m
  | `--  [40m [33mwinreg@1.2.4 [39m [49m
  +--  [40m [33mglob@7.1.2 [39m [49m
  | +--  [40m [33mfs.realpath@1.0.0 [39m [49m
  | +--  [40m [33minflight@1.0.6 [39m [49m
  | | `--  [40m [33mwrappy@1.0.2 [39m [49m
  | +--  [40m [33minherits@2.0.3 [39m [49m
  | +--  [40m [33mminimatch@3.0.4 [39m [49m
  | | `--  [40m [33mbrace-expansion@1.1.8 [39m [49m
  | |   +--  [40m [33mbalanced-match@1.0.0 [39m [49m
  | |   `--  [40m [33mconcat-map@0.0.1 [39m [49m
  | +--  [40m [33monce@1.4.0 [39m [49m
  | `--  [40m [33mpath-is-absolute@1.0.1 [39m [49m
  +--  [40m [33mlodash@4.17.4 [39m [49m
  `--  [40m [33mnan@2.7.0 [39m [49m

**Runtime Error:**

Error: Cannot find module '/home/someone/node/projects/remote_users/node_modules/java/build/Release/nodejavabridge_bindings.node'
    at Function.Module._resolveFilename (module.js:469:15)                                                                     
    at Function.Module._load (module.js:417:25)                                                                                
    at Module.require (module.js:497:17)                                                                                       
    at require (internal/module.js:20:19)                                                                                      
    at Object.<anonymous> (/home/someone/node/projects/remote_users/node_modules/java/lib/nodeJavaBridge.js:21:16)               
    at Module._compile (module.js:570:32)                                                                                      
    at Object.Module._extensions..js (module.js:579:10)                                                                        
    at Module.load (module.js:487:32)                                                                                          
    at tryModuleLoad (module.js:446:12)                                                                                        
    at Function.Module._load (module.js:438:3)

**Comment by skylandL** [comment]
I have the same problem，How do you solve it
