### ISSUE TITLE
unable to load the external jar getting error

### ISSUE THREAD

**Issue by aakashkumar667** [joeferner/node-java#427]
Hi All,
I am also getting the same error i tried all the above suggestions nothing is working for me.
Any help is appreciated.

/opt/demo/node_modules/java/lib/nodeJavaBridge.js:227
var clazz = java.findClassSync(name); // TODO: change to Class.forName when classloader issue is resolved.
^

Error: Could not create class com.aline.demo.Demo1
java.lang.NoClassDefFoundError: com/aline/demo/Demo1
Caused by: java.lang.ClassNotFoundException: com.aline.demo.Demo1
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

at Error (native)
at Java.java.import (/opt/demo/node_modules/java/lib/nodeJavaBridge.js:227:20)
at Object.<anonymous> (/opt/demo/test5.js:9:27)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.runMain (module.js:604:10)
at run (bootstrap_node.js:383:7)

**Comment by RenanChagas** [comment]
Hi,

Im having the same error, anyone find a solution yet ?
