### ISSUE TITLE
error MSB8020: The build tools for v141cannot be found. -  Windows 10

### ISSUE THREAD

**Issue by Ninjaman494** [joeferner/node-java#460]
I'm trying to install node-java using the command `npm install java`. I get the following error:
```
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v141 (Platform Toolset = 'v141') cannot be found. To build using the v141 build tools,
please install v141 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\akash\
Projects\KoreanConjugator\twtkrjs-master\node_modules\java\build\nodejavabridge_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\akash\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\akash\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\akash\Projects\KoreanConjugator\twtkrjs-master\node_modules\java
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

I've already installed the required build tools using `npm install --global --production windows-build-tools`. I've also tried forcing VS17 using `npm install --global --production windows-build-tools --vs2017`

**Comment by Ninjaman494** [comment]
I tried running the command in Intellij's terminal instead of the cmd.exe and it worked. I don't know how that fixed it but I'm not gonna question it lol.
