### ISSUE TITLE
Unable to import class from .jar file

### ISSUE THREAD

**Issue by Mohamed-Abubucker** [joeferner/node-java#461]
Hi,

i am using Ubuntu machine 18.10 and my Java versions is java-11-oracle.

this is my code. i am trying to import a class from .jar file. 

   `
    const java = require("java");

    java.classpath.push(
      path.join(__dirname, "..", "payment-gateway-files", "JavaBridge.jar")
    );

    java.classpath.push(
      path.join(__dirname, "..", "payment-gateway-files", "iPayPipe.jar")
    );

    let obj = java.import("com.fss.plugin.iPayPipe.class");`

its not working for me. i am getting the below error
`Could not create class com.fss.plugin.iPayPipe
java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)`

but actually this i class is available inside that .jar file.

![image](https://user-images.githubusercontent.com/26508192/51110424-a2bea780-181e-11e9-95f6-9a2ace00aa74.png)

![image](https://user-images.githubusercontent.com/26508192/51110462-c2ee6680-181e-11e9-9d60-097b57b09ad6.png)

please help me to resolve this ASAP.

**Comment by mukaschultze** [comment]
Same error here trying to import `net.sf.jasperreports.engine.data.JsonDataSource` from [`jasperreports-6.10.0.jar`](https://github.com/TIBCOSoftware/jasperreports/releases/tag/jr-6-10-0), the class exists in the jar. The error is specific to `JsonDataSource`, other classes are loaded correctly.

Full error:
```log
var clazz = java.findClassSync(name); // TODO: change to Class.forName when classloader issue is resolved.
                   ^

Error: Could not create class net.sf.jasperreports.engine.data.JsonDataSource
java.lang.NoClassDefFoundError: org/apache/commons/beanutils/locale/LocaleConverter
Caused by: java.lang.ClassNotFoundException: org.apache.commons.beanutils.locale.LocaleConverter
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

    at Object.java.import (/home/mukaschultze/test-jasper/node_modules/java/lib/nodeJavaBridge.js:227:20)
```

**Comment by yan130** [comment]
you may need to push the class & test-class file as well. 

refer to https://www.npmjs.com/package/java#using-node-java-in-existing-maven-projects

**Comment by Mohamed-Abubucker** [comment]
@yan130 , thanks for your comment. i already dropped this project as it was taken too much time to get support from community.
