### ISSUE TITLE
/bin/sh: 1: ./find_java_libdir.sh: Permission denied

### ISSUE THREAD

**Issue by kzuzikacs** [joeferner/node-java#466]
We are getting issues when compiling the node-java into the application. We are deploying from Bitbucket into Heroku Application.

+ git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
remote: Compressing source files... done.        
remote: Building source:        
remote: 
remote: -----> JVM Common app detected        
remote: -----> Installing JDK 1.8... done        
remote: -----> Node.js app detected        
remote:                
remote: -----> Creating runtime environment        
remote:                
remote:        NPM_CONFIG_LOGLEVEL=error        
remote:        NODE_ENV=production        
remote:        NODE_MODULES_CACHE=true        
remote:        NODE_VERBOSE=false        
remote:                
remote: -----> Installing binaries        
remote:        engines.node (package.json):  10.11.0        
remote:        engines.npm (package.json):   unspecified (use default)        
remote:                
remote:        Resolving node version 10.11.0...        
remote:        Downloading and installing node 10.11.0...        
remote:        Using default npm version: 6.4.1        
remote:                
remote: -----> Restoring cache        
remote:        - node_modules is checked into source control and cannot be cached        
remote:                
remote: -----> Building dependencies        
remote:        Prebuild detected (node_modules already exists)        
remote:        Rebuilding any native modules        
remote:                
remote:        > java@0.11.0 install /tmp/build_cb482c3d4d1b84097516cad54fdcf2e2/node_modules/java        
remote:        > node-gyp rebuild        
remote:                
remote:        /bin/sh: 1: ./find_java_libdir.sh: Permission denied        
remote:        gyp: Call to './find_java_libdir.sh x64 linux' returned exit status 126 while in binding.gyp. while trying to load binding.gyp        
remote:        gyp ERR! configure error         
remote:        gyp ERR! stack Error: `gyp` failed with exit code: 1        
remote:        gyp ERR! stack     at ChildProcess.onCpExit (/tmp/build_cb482c3d4d1b84097516cad54fdcf2e2/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)        
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:182:13)        
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)        
remote:        gyp ERR! System Linux 4.4.0-1038-aws        
remote:        gyp ERR! command "/tmp/build_cb482c3d4d1b84097516cad54fdcf2e2/.heroku/node/bin/node" "/tmp/build_cb482c3d4d1b84097516cad54fdcf2e2/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"        
remote:        gyp ERR! cwd /tmp/build_cb482c3d4d1b84097516cad54fdcf2e2/node_modules/java        
remote:        gyp ERR! node -v v10.11.0        
remote:        gyp ERR! node-gyp -v v3.8.0        
remote:        gyp ERR! not ok         
remote:        npm ERR! code ELIFECYCLE        
remote:        npm ERR! errno 1        
remote:        npm ERR! java@0.11.0 install: `node-gyp rebuild`        
remote:        npm ERR! Exit status 1        
remote:        npm ERR!         
remote:        npm ERR! Failed at the java@0.11.0 install script.        
remote:        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.        
remote:                
remote:        npm ERR! A complete log of this run can be found in:        
remote:        npm ERR!     /tmp/npmcache.Gkj4C/_logs/2019-03-03T17_45_38_409Z-debug.log

**Comment by JagadishNandeesh** [comment]
Hi kzuzikacs...Could you please let me know whether you are able resolve above issue? How did you resolve it?
