### ISSUE TITLE
Unable to install node-java on Windows (build 1809 October update) with nodeJS 10

### ISSUE THREAD

**Issue by lukechu10** [joeferner/node-java#467]
When I run `npm i java`, I receive the following error:
```cmd
>node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.0 | win32 | x64
gyp info spawn C:\Python27amd64\python.exe
gyp info spawn args [ 'C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\repos\\TagAPI_3\\node_modules\\package\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\admin\\.node-gyp\\10.15.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\admin\\.node-gyp\\10.15.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\admin\\.node-gyp\\10.15.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\repos\\TagAPI_3\\node_modules\\package',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\repos\\TagAPI_3\\node_modules\\package\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  java.cpp
  javaObject.cpp
  javaScope.cpp
  methodCallBaton.cpp
  nodeJavaBridge.cpp
  utils.cpp
  win_delay_load_hook.cc
d:\repos\tagapi_3\node_modules\package\node_modules\nan\nan.h(839): warning C4996: 'node::MakeCallback': was declared d
eprecated (compiling source file ..\src\java.cpp) [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings
.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\node.h(176): note: see declaration of 'node::MakeCallback' (compiling s
  ource file ..\src\java.cpp)
d:\repos\tagapi_3\node_modules\package\node_modules\nan\nan.h(854): warning C4996: 'node::MakeCallback': was declared d
eprecated (compiling source file ..\src\java.cpp) [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings
.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\node.h(169): note: see declaration of 'node::MakeCallback' (compiling s
  ource file ..\src\java.cpp)
d:\repos\tagapi_3\node_modules\package\node_modules\nan\nan.h(869): warning C4996: 'node::MakeCallback': was declared d
eprecated (compiling source file ..\src\java.cpp) [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings
.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\node.h(162): note: see declaration of 'node::MakeCallback' (compiling s
  ource file ..\src\java.cpp)
d:\repos\tagapi_3\node_modules\package\node_modules\nan\nan.h(1648): warning C4996: 'node::MakeCallback': was declared
deprecated (compiling source file ..\src\java.cpp) [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_binding
s.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\node.h(176): note: see declaration of 'node::MakeCallback' (compiling s
  ource file ..\src\java.cpp)
d:\repos\tagapi_3\node_modules\package\node_modules\nan\nan.h(839): warning C4996: 'node::MakeCallback': was declared d
eprecated (compiling source file ..\src\javaObject.cpp) [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bi
ndings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\node.h(176): note: see declaration of 'node::MakeCallback' (compiling s
  ource file ..\src\javaObject.cpp)
d:\repos\tagapi_3\node_modules\package\node_modules\nan\nan.h(854): warning C4996: 'node::MakeCallback': was declared d
eprecated (compiling source file ..\src\javaObject.cpp) [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bi
ndings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\node.h(169): note: see declaration of 'node::MakeCallback' (compiling s
  ource file ..\src\javaObject.cpp)
d:\repos\tagapi_3\node_modules\package\node_modules\nan\nan.h(869): warning C4996: 'node::MakeCallback': was declared d
eprecated (compiling source file ..\src\javaObject.cpp) [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bi
ndings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\node.h(162): note: see declaration of 'node::MakeCallback' (compiling s
  ource file ..\src\javaObject.cpp)
d:\repos\tagapi_3\node_modules\package\node_modules\nan\nan.h(839): warning C4996: 'node::MakeCallback': was declared d
eprecated (compiling source file ..\src\nodeJavaBridge.cpp)d:\repos\tagapi_3\node_modules\package\node_modules\nan\nan.
h(1648): warning C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\src\javaObject.cpp) [D:
\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\node.h(176): note: see declaration of 'node::MakeCallback' (compiling s
  ource file ..\src\javaObject.cpp)

  c:\users\admin\.node-gyp\10.15.0\include\node\node.h(176): note: see declaration of 'node::MakeCallback' (compiling s
  ource file ..\src\nodeJavaBridge.cpp)
d:\repos\tagapi_3\node_modules\package\node_modules\nan\nan.h(854): warning C4996: 'node::MakeCallback': was declared d
eprecated (compiling source file ..\src\nodeJavaBridge.cpp)d:\repos\tagapi_3\node_modules\package\node_modules\nan\nan.
h(839): warning C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\src\utils.cpp) [D:\repos
\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]

d:\repos\tagapi_3\node_modules\package\src\java.cpp(139): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declar
ed deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
d:\repos\tagapi_3\node_modules\package\src\java.cpp(147): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declar
ed deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
d:\repos\tagapi_3\node_modules\package\src\java.cpp(155): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declar
ed deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
  c:\users\admin\.node-gyp\10.15.0\include\node\node.h(169): note: see declaration of 'node::MakeCallback' (compiling s
  ource file ..\src\nodeJavaBridge.cpp)c:\users\admin\.node-gyp\10.15.0\include\node\node.h(176): note: see declaration
   of 'node::MakeCallback' (compiling source file ..\src\utils.cpp)

d:\repos\tagapi_3\node_modules\package\node_modules\nan\nan.h(869): warning C4996: 'node::MakeCallback': was declared d
eprecated (compiling source file ..\src\nodeJavaBridge.cpp)d:\repos\tagapi_3\node_modules\package\node_modules\nan\nan.
h(854): warning C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\src\utils.cpp)d:\repos\t
agapi_3\node_modules\package\src\java.cpp(207): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declared depreca
ted [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]

  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
d:\repos\tagapi_3\node_modules\package\src\java.cpp(213): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declar
ed deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]

  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
d:\repos\tagapi_3\node_modules\package\src\java.cpp(236): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declar
ed deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\node.h(162): note: see declaration of 'node::MakeCallback' (compiling s
  ource file ..\src\nodeJavaBridge.cpp)c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration
  of 'v8::String::Utf8Value::Utf8Value'
  c:\users\admin\.node-gyp\10.15.0\include\node\node.h(169): note: see declaration of 'node::MakeCallback' (compiling s
  ource file ..\src\utils.cpp)
d:\repos\tagapi_3\node_modules\package\src\java.cpp(290): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declar
ed deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'

d:\repos\tagapi_3\node_modules\package\src\java.cpp(313): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declar
ed deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
d:\repos\tagapi_3\node_modules\package\node_modules\nan\nan.h(869): warning C4996: 'node::MakeCallback': was declared d
eprecated (compiling source file ..\src\utils.cpp)d:\repos\tagapi_3\node_modules\package\node_modules\nan\nan.h(1648):
warning C4996: 'node::MakeCallback': was declared deprecated (compiling source file ..\src\nodeJavaBridge.cpp) [D:\repo
s\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
d:\repos\tagapi_3\node_modules\package\src\java.cpp(360): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declar
ed deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]

  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
  c:\users\admin\.node-gyp\10.15.0\include\node\node.h(162): note: see declaration of 'node::MakeCallback' (compiling s
  ource file ..\src\utils.cpp)
  c:\users\admin\.node-gyp\10.15.0\include\node\node.h(176): note: see declaration of 'node::MakeCallback' (compiling s
  ource file ..\src\nodeJavaBridge.cpp)d:\repos\tagapi_3\node_modules\package\src\java.cpp(403): warning C4996: 'v8::St
  ring::Utf8Value::Utf8Value': was declared deprecated
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'

d:\repos\tagapi_3\node_modules\package\src\java.cpp(445): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declar
ed deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
d:\repos\tagapi_3\node_modules\package\src\java.cpp(556): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declar
ed deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
d:\repos\tagapi_3\node_modules\package\src\java.cpp(557): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declar
ed deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
d:\repos\tagapi_3\node_modules\package\node_modules\nan\nan.h(1648): warning C4996: 'node::MakeCallback': was declared
deprecated (compiling source file ..\src\utils.cpp)d:\repos\tagapi_3\node_modules\package\src\javaobject.cpp(143): warn
ing C4996: 'v8::String::Utf8Value::Utf8Value': was declared deprecated [D:\repos\TagAPI_3\node_modules\package\build\no
dejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'

d:\repos\tagapi_3\node_modules\package\src\java.cpp(600): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declar
ed deprecatedd:\repos\tagapi_3\node_modules\package\src\javaobject.cpp(179): warning C4996: 'v8::String::Utf8Value::Utf
8Value': was declared deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]

  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'

d:\repos\tagapi_3\node_modules\package\src\java.cpp(601): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declar
ed deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
d:\repos\tagapi_3\node_modules\package\src\java.cpp(647): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declar
ed deprecatedd:\repos\tagapi_3\node_modules\package\src\javaobject.cpp(230): warning C4996: 'v8::String::Utf8Value::Utf
8Value': was declared deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]

  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'

  c:\users\admin\.node-gyp\10.15.0\include\node\node.h(176): note: see declaration of 'node::MakeCallback' (compiling s
  ource file ..\src\utils.cpp)d:\repos\tagapi_3\node_modules\package\src\javaobject.cpp(281): warning C4996: 'v8::Strin
  g::Utf8Value::Utf8Value': was declared deprecated
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
d:\repos\tagapi_3\node_modules\package\src\java.cpp(687): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declar
ed deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
d:\repos\tagapi_3\node_modules\package\src\java.cpp(724): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declar
ed deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'

d:\repos\tagapi_3\node_modules\package\src\java.cpp(753): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declar
ed deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
d:\repos\tagapi_3\node_modules\package\src\java.cpp(881): warning C4996: 'v8::String::Utf8Value::Utf8Value': was declar
ed deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
d:\repos\tagapi_3\node_modules\package\src\java.cpp(1003): warning C4996: 'v8::String::Utf8Value::Utf8Value': was decla
red deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
d:\repos\tagapi_3\node_modules\package\src\java.cpp(1081): warning C4996: 'v8::String::Utf8Value::Utf8Value': was decla
red deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
d:\repos\tagapi_3\node_modules\package\src\java.cpp(1082): warning C4996: 'v8::String::Utf8Value::Utf8Value': was decla
red deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
d:\repos\tagapi_3\node_modules\package\node_modules\nan\nan.h(839): warning C4996: 'node::MakeCallback': was declared d
eprecated (compiling source file ..\src\methodCallBaton.cpp) [D:\repos\TagAPI_3\node_modules\package\build\nodejavabrid
ge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\node.h(176): note: see declaration of 'node::MakeCallback' (compiling s
  ource file ..\src\methodCallBaton.cpp)d:\repos\tagapi_3\node_modules\package\src\java.cpp(1128): warning C4996: 'v8::
  String::Utf8Value::Utf8Value': was declared deprecated
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
d:\repos\tagapi_3\node_modules\package\src\java.cpp(1129): warning C4996: 'v8::String::Utf8Value::Utf8Value': was decla
red deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'

d:\repos\tagapi_3\node_modules\package\node_modules\nan\nan.h(854): warning C4996: 'node::MakeCallback': was declared d
eprecated (compiling source file ..\src\methodCallBaton.cpp)d:\repos\tagapi_3\node_modules\package\src\java.cpp(1189):
warning C4996: 'v8::String::Utf8Value::Utf8Value': was declared deprecated [D:\repos\TagAPI_3\node_modules\package\buil
d\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'
d:\repos\tagapi_3\node_modules\package\src\java.cpp(1283): warning C4996: 'v8::String::Utf8Value::Utf8Value': was decla
red deprecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2891): note: see declaration of 'v8::String::Utf8Value::Utf8Value'

  c:\users\admin\.node-gyp\10.15.0\include\node\node.h(169): note: see declaration of 'node::MakeCallback' (compiling s
  ource file ..\src\methodCallBaton.cpp)
d:\repos\tagapi_3\node_modules\package\node_modules\nan\nan.h(869): warning C4996: 'node::MakeCallback': was declared d
eprecated (compiling source file ..\src\methodCallBaton.cpp) [D:\repos\TagAPI_3\node_modules\package\build\nodejavabrid
ge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\node.h(162): note: see declaration of 'node::MakeCallback' (compiling s
  ource file ..\src\methodCallBaton.cpp)
d:\repos\tagapi_3\node_modules\package\node_modules\nan\nan.h(1648): warning C4996: 'node::MakeCallback': was declared
deprecated (compiling source file ..\src\methodCallBaton.cpp) [D:\repos\TagAPI_3\node_modules\package\build\nodejavabri
dge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\node.h(176): note: see declaration of 'node::MakeCallback' (compiling s
  ource file ..\src\methodCallBaton.cpp)
d:\repos\tagapi_3\node_modules\package\src\utils.cpp(342): warning C4996: 'v8::String::Value::Value': was declared depr
ecated [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
  c:\users\admin\.node-gyp\10.15.0\include\node\v8.h(2916): note: see declaration of 'v8::String::Value::Value'
     Creating library D:\repos\TagAPI_3\node_modules\package\build\Release\nodejavabridge_bindings.lib and object D:\re
  pos\TagAPI_3\node_modules\package\build\Release\nodejavabridge_bindings.exp
java.obj : error LNK2001: unresolved external symbol __imp_JNI_CreateJavaVM [D:\repos\TagAPI_3\node_modules\package\bui
ld\nodejavabridge_bindings.vcxproj]
D:\repos\TagAPI_3\node_modules\package\build\Release\nodejavabridge_bindings.node : fatal error LNK1120: 1 unresolved e
xternals [D:\repos\TagAPI_3\node_modules\package\build\nodejavabridge_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\admin\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\repos\TagAPI_3\node_modules\package
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

It seems like some methods from the api that `node-java` is using has been deprecated. 
Any help is welcome

**Comment by lukechu10** [comment]
Resolved:
Run `npm I java --arch=ia32` beaucause it doesn't work on 64bit
