### ISSUE TITLE
Java 12 NullPointerException

### ISSUE THREAD

**Issue by uri-canva** [joeferner/node-java#468]
After upgrading to Java 12:

```
Error: Error running instance method
java.lang.NullPointerException
    at java.base/jdk.internal.reflect.Reflection.verifyMemberAccess(Reflection.java:130)
    at java.base/java.lang.reflect.AccessibleObject.slowVerifyAccess(AccessibleObject.java:673)
    at java.base/java.lang.reflect.AccessibleObject.verifyAccess(AccessibleObject.java:666)
    at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:638)
    at java.base/java.lang.reflect.Method.invoke(Method.java:559)

    at Java.java.import (/Users/anton/projects/canva-s/web/node_modules/java/lib/nodeJavaBridge.js:240:52)
```

Might be related to https://bugs.openjdk.java.net/browse/JDK-8221530, found through https://github.com/s-u/rJava/issues/175.

**Comment by KNejad** [comment]
I can confirm I have the same issue. I just upgraded to Java 12 and the same error is occurring. Once I downgraded it started working again. Although it has been fixed for 12.0.2

**Comment by JayenLee** [comment]
I have the same issue


Error: Error creating class
java.lang.NullPointerException
        at java.base/jdk.internal.reflect.Reflection.verifyMemberAccess(Reflection.java:130)
        at java.base/java.lang.reflect.AccessibleObject.slowVerifyAccess(AccessibleObject.java:673)
        at java.base/java.lang.reflect.AccessibleObject.verifyAccess(AccessibleObject.java:666)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:638)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:490)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)

**Comment by karocksjoeli** [comment]
Any update on this ? 
I am using java 18

java 18 2022-03-22
Java(TM) SE Runtime Environment (build 18+36-2087)
Java HotSpot(TM) 64-Bit Server VM (build 18+36-2087, mixed mode, sharing)

on Windows10

**Comment by weisensee** [comment]
@karocksjoeli I had the same problem. Downgraded to 17 and things started working...

**Comment by Sooyap** [comment]
I can confirm that downgrading from JDK 18.0.1.1 to JDK 17.0.3.1 resolved this issue for me.
