### ISSUE TITLE
Nodejs 12

### ISSUE THREAD

**Issue by shawn-mcginty** [joeferner/node-java#470]
Error when trying to install using
node: v12.1.0
npm: 6.9.0

```
$ npm install

> java@0.11.0 install /Users/shawn/tmp-thing/node_modules/java
> node-gyp rebuild

make: Entering directory '/Users/shawn/tmp-thing/node_modules/java/build'
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
In file included from ../node_modules/nan/nan.h:221:
In file included from ../node_modules/nan/nan_converters.h:67:
../node_modules/nan/nan_converters_43_inl.h:22:1: warning: 'ToBoolean' is deprecated: ToBoolean can never throw. Use Local version. [-Wdeprecated-declarations]
X(Boolean)
^
../node_modules/nan/nan_converters_43_inl.h:18:12: note: expanded from macro 'X'
      val->To ## TYPE(isolate->GetCurrentContext())                            \
           ^
<scratch space>:175:1: note: expanded from here
ToBoolean
^
/Users/shawn/.node-gyp/12.1.0/include/node/v8.h:2523:3: note: 'ToBoolean' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("ToBoolean can never throw. Use Local version.",
  ^
/Users/shawn/.node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
In file included from ../node_modules/nan/nan.h:221:
In file included from ../node_modules/nan/nan_converters.h:67:
../node_modules/nan/nan_converters_43_inl.h:40:1: warning: 'BooleanValue' is deprecated: BooleanValue can never throw. Use Isolate version. [-Wdeprecated-declarations]
X(bool, Boolean)
^
../node_modules/nan/nan_converters_43_inl.h:37:15: note: expanded from macro 'X'
  return val->NAME ## Value(isolate->GetCurrentContext());                     \
              ^
<scratch space>:182:1: note: expanded from here
BooleanValue
^
/Users/shawn/.node-gyp/12.1.0/include/node/v8.h:2561:3: note: 'BooleanValue' has been explicitly marked deprecated here
  V8_DEPRECATED("BooleanValue can never throw. Use Isolate version.",
  ^
/Users/shawn/.node-gyp/12.1.0/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
In file included from ../node_modules/nan/nan.h:222:
In file included from ../node_modules/nan/nan_new.h:189:
../node_modules/nan/nan_implementation_12_inl.h:103:42: error: no viable conversion from 'v8::Isolate *' to 'Local<v8::Context>'
  return scope.Escape(v8::Function::New( isolate
                                         ^~~~~~~
/Users/shawn/.node-gyp/12.1.0/include/node/v8.h:183:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::Isolate *' to 'const v8::Local<v8::Context> &' for 1st argument
class Local {
      ^
/Users/shawn/.node-gyp/12.1.0/include/node/v8.h:183:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::Isolate *' to 'v8::Local<v8::Context> &&' for 1st argument
/Users/shawn/.node-gyp/12.1.0/include/node/v8.h:187:13: note: candidate template ignored: could not match 'Local<type-parameter-0-0>' against 'v8::Isolate *'
  V8_INLINE Local(Local<S> that)
            ^
/Users/shawn/.node-gyp/12.1.0/include/node/v8.h:4126:22: note: passing argument to parameter 'context' here
      Local<Context> context, FunctionCallback callback,
                     ^
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
../node_modules/nan/nan.h:1064:44: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString(v8::Isolate::GetCurrent());
                                           ^
/Users/shawn/.node-gyp/12.1.0/include/node/v8.h:2543:3: note: 'ToString' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shawn/.node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
../node_modules/nan/nan.h:1855:28: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
                           ^
/Users/shawn/.node-gyp/12.1.0/include/node/v8.h:3358:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shawn/.node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
../node_modules/nan/nan.h:1861:28: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    New(persistentHandle)->Set(key, value);
                           ^
/Users/shawn/.node-gyp/12.1.0/include/node/v8.h:3358:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shawn/.node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
../node_modules/nan/nan.h:1867:28: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    New(persistentHandle)->Set(index, value);
                           ^
/Users/shawn/.node-gyp/12.1.0/include/node/v8.h:3367:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/shawn/.node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
../node_modules/nan/nan.h:1873:32: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
        New(persistentHandle)->Get(New(key).ToLocalChecked()));
                               ^
/Users/shawn/.node-gyp/12.1.0/include/node/v8.h:3412:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/shawn/.node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
../node_modules/nan/nan.h:1879:48: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    return scope.Escape(New(persistentHandle)->Get(key));
                                               ^
/Users/shawn/.node-gyp/12.1.0/include/node/v8.h:3412:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(Local<Value> key));
  ^
/Users/shawn/.node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
../node_modules/nan/nan.h:1884:48: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
    return scope.Escape(New(persistentHandle)->Get(index));
                                               ^
/Users/shawn/.node-gyp/12.1.0/include/node/v8.h:3416:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(uint32_t index));
  ^
/Users/shawn/.node-gyp/12.1.0/include/node/v8config.h:322:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
In file included from ../node_modules/nan/nan.h:2698:
../node_modules/nan/nan_object_wrap.h:24:25: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(persistent().IsNearDeath());
           ~~~~~~~~~~~~ ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
In file included from ../node_modules/nan/nan.h:2698:
../node_modules/nan/nan_object_wrap.h:67:18: warning: 'MarkIndependent' is deprecated: Weak objects are always considered independent. Use TracedGlobal when trying to use EmbedderHeapTracer. Use a strong handle when trying to keep an object alive.
      [-Wdeprecated-declarations]
    persistent().MarkIndependent();
                 ^
/Users/shawn/.node-gyp/12.1.0/include/node/v8.h:563:3: note: 'MarkIndependent' has been explicitly marked deprecated here
  V8_DEPRECATED(
  ^
/Users/shawn/.node-gyp/12.1.0/include/node/v8config.h:307:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:9:
In file included from ../node_modules/nan/nan.h:2698:
../node_modules/nan/nan_object_wrap.h:124:26: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(wrap->handle_.IsNearDeath());
           ~~~~~~~~~~~~~ ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
                        ^
In file included from ../src/java.cpp:1:
../src/java.h:19:24: error: no template named 'Handle' in namespace 'v8'
  static void Init(v8::Handle<v8::Object> target);
                   ~~~~^
In file included from ../src/java.cpp:7:
../src/javaObject.h:16:24: error: no template named 'Handle' in namespace 'v8'
  static void Init(v8::Handle<v8::Object> target);
                   ~~~~^
../src/java.cpp:52:23: error: variable has incomplete type 'void'
/*static*/ void Java::Init(v8::Handle<v8::Object> target) {
                      ^
../src/java.cpp:52:49: error: expected '(' for function-style cast or type construction
/*static*/ void Java::Init(v8::Handle<v8::Object> target) {
                                      ~~~~~~~~~~^
../src/java.cpp:52:32: error: no member named 'Handle' in namespace 'v8'
/*static*/ void Java::Init(v8::Handle<v8::Object> target) {
                           ~~~~^
../src/java.cpp:52:51: error: use of undeclared identifier 'target'
/*static*/ void Java::Init(v8::Handle<v8::Object> target) {
                                                  ^
../src/java.cpp:52:58: error: expected ';' after top level declarator
/*static*/ void Java::Init(v8::Handle<v8::Object> target) {
                                                         ^
                                                         ;
10 warnings and 10 errors generated.```

**Comment by tripower** [comment]
I have similar problems
and I need NodeJS 12 because update of electron (5.0.1) has to be done

**Comment by scottbell** [comment]
Would love to use the upcoming LTS too please!

**Comment by joeferner** [comment]
I have a branch started https://github.com/joeferner/node-java/tree/node12 but it's slow going

**Comment by huang-xiao-jian** [comment]
v12 seems not supported yet

**Comment by jeffrichiefs** [comment]
I needed to version lock to Node 8 and Python2 to get this to build.

**Comment by PrashantN86** [comment]
Still getting the same error while installing node-java as a dependency for node-jdbc

Snippet of the stack trace as follows:

```
"../src/utils.h:120:58: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::String>&)’",
 "   v8::String::Utf8Value _##ARGNAME##_val(_##ARGNAME##_obj);                                  \\",
 "                                                          ^",
 "../src/java.cpp:1189:3: note: in expansion of macro ‘ARGS_FRONT_STRING’",
 "   ARGS_FRONT_STRING(className);",
 "   ^",
 "../src/utils.h:120:58: note: candidate is:",
 "   v8::String::Utf8Value _##ARGNAME##_val(_##ARGNAME##_obj);                                  \\",
 "                                                          ^",
 "../src/java.cpp:1189:3: note: in expansion of macro ‘ARGS_FRONT_STRING’",
 "   ARGS_FRONT_STRING(className);",
 "   ^",
 "In file included from ../src/java.h:5:0,
",
 "                 from ../src/java.cpp:1:",
 "/home/ec2-user/.cache/node-gyp/12.13.0/include/node/v8.h:3039:5: note: v8::String::Utf8Value::Utf8Value(v8::Isolate*,
 v8::Local<v8::Value>)",
 "     Utf8Value(Isolate* isolate,
 Local<v8::Value> obj);",
 "     ^",
 "/home/ec2-user/.cache/node-gyp/12.13.0/include/node/v8.h:3039:5: note:   candidate expects 2 arguments,
 1 provided",
 "../src/java.cpp: In function ‘void EIO_AfterCallJs(uv_work_t*,
 int)’:",
 "../src/java.cpp:1243:3: error: ‘Handle’ is not a member of ‘v8’",
 "   v8::Handle<v8::Value>* argv;",
 "   ^",
 "../src/java.cpp:1243:23: error: expected primary-expression before ‘>’ token",
 "   v8::Handle<v8::Value>* argv;",
 "                       ^",
 "../src/java.cpp:1243:26: error: ‘argv’ was not declared in this scope",
 "   v8::Handle<v8::Value>* argv;",
 "                          ^",
 "../src/java.cpp:1250:138: warning: ‘v8::Local<v8::Value> v8::Object::Get(v8::Local<v8::Value>)’ is deprecated (declared at /home/ec2-user/.cache/node-gyp/12.13.0/include/node/v8.h:3457): Use maybe version [-Wdeprecated-declarations]",
 "   v8::Local<v8::Value> fnObj = dynamicProxyDataFunctions->Get(Nan::New<v8::String>(dynamicProxyData->methodName.c_str()).ToLocalChecked());",
 "                                                                                                                                          ^",
 "../src/java.cpp:1272:14: error: expected type-specifier",
 "   argv = new v8::Handle<v8::Value>[argc];",
 "              ^",
 "../src/java.cpp:1272:14: error: expected ‘;’",
 "../src/java.cpp:1274:28: warning: ‘v8::Local<v8::Value> v8::Object::Get(uint32_t)’ is deprecated (declared at /home/ec2-user/.cache/node-gyp/12.13.0/include/node/v8.h:3461): Use maybe version [-Wdeprecated-declarations]",
 "     argv[i] = v8Args->Get(i);",
 "                            ^",
 "../src/java.cpp:1280:12: error: type ‘<type error>’ argument given to ‘delete’,
 expected pointer",
 "   delete[] argv;",
 "            ^",
 "../src/java.cpp:1283:60: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::String>)’",
 "     v8::String::Utf8Value message(tryCatch.Message()->Get());",
 "                                                            ^",
 "../src/java.cpp:1283:60: note: candidate is:",
 "In file included from ../src/java.h:5:0,
",
 "                 from ../src/java.cpp:1:",
 "/home/ec2-user/.cache/node-gyp/12.13.0/include/node/v8.h:3039:5: note: v8::String::Utf8Value::Utf8Value(v8::Isolate*,
 v8::Local<v8::Value>)",
 "     Utf8Value(Isolate* isolate,
 Local<v8::Value> obj);",
 "     ^",
 "/home/ec2-user/.cache/node-gyp/12.13.0/include/node/v8.h:3039:5: note:   candidate expects 2 arguments,
 1 provided",
 "make: *** [Release/obj.target/nodejavabridge_bindings/src/java.o] Error 1",
 "gyp ERR! build error ",
 "gyp ERR! stack Error: `make` failed with exit code: 2",
 "gyp ERR! stack     at ChildProcess.onExit (/opt/node-v12.13.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)",
 "gyp ERR! stack     at ChildProcess.emit (events.js:210:5)",
 "gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)",
 "gyp ERR! System Linux 3.10.0-1062.1.2.el7.x86_64",
 "gyp ERR! command \"/opt/node-v12.13.0-linux-x64/bin/node\" \"/opt/node-v12.13.0-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"",
 "gyp ERR! cwd /opt/nodejs/ramp_services/node_modules/jdbc/node_modules/java",
 "gyp ERR! node -v v12.13.0",
 "gyp ERR! node-gyp -v v5.0.5",
 "gyp ERR! not ok ",
 "npm WARN babel-plugin-styled-components@1.10.6 requires a peer of styled-components@>= 2 but none is installed. You must install peer dependencies yourself.",
 "npm WARN ramp-api-daas@0.0.68 No repository field.",
 "npm WARN ramp-api-daas@0.0.68 No license field.",
 "npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):",
 "npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {\"os\":\"darwin\",
\"arch\":\"any\"} (current: {\"os\":\"linux\",
\"arch\":\"x64\"})",
 "",
 "npm ERR! code ELIFECYCLE",
 "npm ERR! errno 1",
 "npm ERR! java@0.9.1 install: `node-gyp rebuild`",
 "npm ERR! Exit status 1",
 "npm ERR! ",
 "npm ERR! Failed at the java@0.9.1 install script.",
 "npm ERR! This is probably not a problem with npm. There is likely additional logging output above.",
 "",
 "npm ERR! A complete log of this run can be found in:",
 "npm ERR!     /home/ec2-user/.npm/_logs/2020-01-07T20_51_52_159Z-debug.log"],
 "stdout": "\n> java@0.9.1 install /opt/nodejs/ramp_services/node_modules/jdbc/node_modules/java\n> node-gyp rebuild\n\nmake: Entering directory `/opt/nodejs/ramp_services/node_modules/jdbc/node_modules/java/build'\n  CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o\nmake: Leaving directory `/opt/nodejs/ramp_services/node_modules/jdbc/node_modules/java/build'",
 "stdout_lines": ["",
 "> java@0.9.1 install /opt/nodejs/ramp_services/node_modules/jdbc/node_modules/java",
 "> node-gyp rebuild",
 "",
 "make: Entering directory `/opt/nodejs/ramp_services/node_modules/jdbc/node_modules/java/build'",
 "  CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o",
 "make: Leaving directory `/opt/nodejs/ramp_services/node_modules/jdbc/node_modules/java/build'"]}

```

**Comment by PrashantN86** [comment]
Never mind... The node-jdbc repository is not being maintained and is referring to an older version on node-java. So not a node-java issue.

node-jdbc issue : https://github.com/CraZySacX/node-jdbc/issues/199
