### ISSUE TITLE
Unable to execute test.js

### ISSUE THREAD

**Issue by kevinaism** [joeferner/node-java#475]
When I tried to execute test.js file:
```
var java = require('java');
var javaLangSystem = java.import('java.lang.System');

javaLangSystem.out.printlnSync('Hello World');
```

It generates error message as follows:
```
Error: Error creating class
java.lang.NullPointerException
        at java.base/jdk.internal.reflect.Reflection.verifyMemberAccess(Reflection.java:130)
        at java.base/java.lang.reflect.AccessibleObject.slowVerifyAccess(AccessibleObject.java:673)
        at java.base/java.lang.reflect.AccessibleObject.verifyAccess(AccessibleObject.java:666)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:638)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:490)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)

    at /Users/oneshop/Documents/hkirc_api/index.js:28:19
    at /Users/oneshop/Documents/hkirc_api/node_modules/async/dist/async.js:3888:9
    at /Users/oneshop/Documents/hkirc_api/node_modules/async/dist/async.js:473:16
    at replenish (/Users/oneshop/Documents/hkirc_api/node_modules/async/dist/async.js:1006:25)
    at /Users/oneshop/Documents/hkirc_api/node_modules/async/dist/async.js:1016:9
    at eachOfLimit (/Users/oneshop/Documents/hkirc_api/node_modules/async/dist/async.js:1041:24)
    at /Users/oneshop/Documents/hkirc_api/node_modules/async/dist/async.js:1046:16
    at _parallel (/Users/oneshop/Documents/hkirc_api/node_modules/async/dist/async.js:3879:5)
    at Object.series (/Users/oneshop/Documents/hkirc_api/node_modules/async/dist/async.js:4735:5)
    at Immediate.initializeAll (/Users/oneshop/Documents/hkirc_api/node_modules/java/lib/nodeJavaBridge.js:135:9)
```

I am currently suing node v10 and Java 8 as the runtime. Please help or suggest. Thanks

**Comment by zuohuadong** [comment]
Linux  node10 && java8 is OK
