### ISSUE TITLE
Failed at the java@0.12.1 install script. Seen on travis-ci and aws

### ISSUE THREAD

**Issue by danielwsutton** [joeferner/node-java#504]
Failed at the java@0.12.1 install script. Seen on travis-ci and aws

https://travis-ci.org/github/joeferner/node-java/jobs/717671107

```
gyp ERR! stack Error: `make` failed with exit code: 2

gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)

gyp ERR! stack     at ChildProcess.emit (events.js:315:20)

gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

gyp ERR! System Linux 4.15.0-1077-gcp

gyp ERR! command "/home/travis/.nvm/versions/node/v12.18.3/bin/node" "/home/travis/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

gyp ERR! cwd /home/travis/build/joeferner/node-java

gyp ERR! node -v v12.18.3

gyp ERR! node-gyp -v v5.1.0

gyp ERR! not ok 

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! java@0.12.1 install: `node-gyp rebuild`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the java@0.12.1 install script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR!     /home/travis/.npm/_logs/2020-08-13T17_33_33_699Z-debug.log

The command "npm install" failed and exited with 1 during .
```

**Comment by danielwsutton** [comment]
If you remove the line `'-ljli'` from `binding.gyp` this build issue is resolved.

Or if you downgrade your jdk to 1.8. any jdk 9+ it breaks unless you remove the reference to `'-ljli'`

I search for a long time to figure out what jli is for, but couldn't find anything...

**Comment by danielwsutton** [comment]
similar issue, i'll take a look > https://github.com/joeferner/node-java/issues/497

**Comment by danielwsutton** [comment]
> lib_dir="${jre_dir}/jli"

I forked this change, https://github.com/danielwsutton/node-java/commit/1e30ba786a6965fd8df2b643a5d962b06891d4fb

From:

```
lib_dir="${jre_dir}/jli" 
```

To:

```
if [[ -f ${jre_dir}/jli/libjli.dylib ]]; then lib_dir="${jre_dir}"/jli; else lib_dir="${jre_dir}"; fi
```

So far it seems to be working,

I testing on adoptopenjdk8 and adoptopenjdk12 , your mileage may vary,

**Comment by danielwsutton** [comment]
I did run into a new issue, but can't seem to repro it locally, only when running it on aws,

  CXX(target) Release/obj.target/nodejavabridge_bindings/src/utils.o
../src/utils.cpp:488:16: error: no member named 'GetBackingStore' in 'v8::ArrayBuffer'
    memcpy(ab->GetBackingStore()->Data(), elems, length);
           ~~  ^

**Comment by danielwsutton** [comment]
The above issue with no member named 'GetBackingStore' was resolved by using node 14.8.0

It seems like when you switch to a new version of Java, it forces you into a newer version of Node as well.
