### ISSUE TITLE
function 'Set' is ambiguous

### ISSUE THREAD

**Issue by wjs4572** [joeferner/node-java#506]
I am receiving the following message when I try to perform the build:

`nw-gyp build --target=0.47.0 >out.txt`

**..\src\javaObject.cpp(245): error : call to member function 'Set' is ambiguous [<PROJECT_PATH>\node_modules\java\build\nodejavabridge_bindings.vcxproj]**

```nw-gyp build --target=0.47.0 >out.txt
gyp info it worked if it ends with ok
gyp info using nw-gyp@3.6.5
gyp info using node@12.18.2 | win32 | x64
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:CLToolExe=clang-cl.exe',
gyp info spawn args   '/p:LinkToolExe=lld-link.exe',
gyp info spawn args   '/p:CLToolPath=C:\\Users\\<USER_NAME>\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\clang',
gyp info spawn args   '/p:LinkToolPath=C:\\Users\\<USER_NAME>\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\clang',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\<USER_NAME>\AppData\Roaming\npm\node_modules\nw-gyp\lib\build.js:271:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\<USER_NAME>\\AppData\\Roaming\\npm\\node_modules\\nw-gyp\\bin\\nw-gyp.js" "build" "--target=0.47.0"
gyp ERR! cwd <PROJECT_PATH>\node_modules\java
gyp ERR! node -v v12.18.2
gyp ERR! nw-gyp -v v3.6.5
gyp ERR! not ok
```

The contents of out.txt:

```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
clang-cl : warning : argument unused during compilation: '/MP' [-Wunused-command-line-argument] [<PROJECT_PATH>\node_modules\java\build\nodejavabridge_bindings.vcxproj]
clang-cl : warning : argument unused during compilation: '/Gm-' [-Wunused-command-line-argument] [<PROJECT_PATH>\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\javaObject.cpp(245): error : call to member function 'Set' is ambiguous [<PROJECT_PATH>\node_modules\java\build\nodejavabridge_bindings.vcxproj]
  ..\..\nan/nan_callbacks_12_inl.h(46): note: candidate function
  ..\..\nan/nan_callbacks_12_inl.h(56): note: candidate function
  ..\..\nan/nan_callbacks_12_inl.h(61): note: candidate function
  ..\..\nan/nan_callbacks_12_inl.h(51): note: candidate function
  ..\..\nan/nan_callbacks_12_inl.h(27): note: candidate template ignored: could not match 'Local<type-parameter-0-0>' against 'long'
  ..\..\nan/nan_callbacks_12_inl.h(32): note: candidate template ignored: could not match 'Global<type-parameter-0-0>' against 'long'
  ..\..\nan/nan_callbacks_12_inl.h(89): note: candidate template ignored: could not match 'S *' against 'jint' (aka 'long')
```

**Comment by wjs4572** [comment]
So found a could of things.  First, the packages.json shows 0.12.1, so I have changed the above target parameter to 0.12.1.  When run this still produces the same error, namely:

```
clang-cl : warning : argument unused during compilation: '/Gm-' [-Wunused-command-line-argument] [<PROJECT_PATH>\node_modules\java\build\nodejavabridge_bindings.vcxproj]
..\src\javaObject.cpp(245): error : call to member function 'Set' is ambiguous [<PROJECT_PATH>\node_modules\java\build\nodejavabridge_bindings.vcxproj]
```
So looking at the javaObject.cpp file at line 245 shows the following:

```
Nan::Utf8String propertyCStr(property);
  std::string propertyStr = *propertyCStr;
  jobject field = javaFindField(env, self->m_class, propertyStr);
  if(field == NULL) {
    if(propertyStr == "length") {
      jclass classClazz = env->FindClass("java/lang/Class");
      jmethodID class_isArray = env->GetMethodID(classClazz, "isArray", "()Z");
      jboolean isArray = env->CallBooleanMethod(self->m_class, class_isArray);
      if(isArray) {
        jclass arrayClass = env->FindClass("java/lang/reflect/Array");
        jmethodID array_getLength = env->GetStaticMethodID(arrayClass, "getLength", "(Ljava/lang/Object;)I");
        jint arrayLength = env->CallStaticIntMethod(arrayClass, array_getLength, self->m_obj);
        assertNoException(env);
        info.GetReturnValue().Set(arrayLength);
        return;
      }
    }
```

Where the line with the Set method appears to be called from what ever object is returned by the GetReturnValue method.

**info.GetReturnValue().Set(arrayLength);**

Hence the ambiguity, as it appears the compiler is confused as to what type the GetReturnValue method is expected to return.  Splitting this statement into two and making that specification would likely fix this issue.

I have only just started looking at this code base, so I am not sure if there are different types of return values expected.  Is this call overloaded?

**Comment by wjs4572** [comment]
I finally got something to work.  I am not sure what npm does differently or why the install needs to be done twice.

Basically, if you run"

```npm install java```

From the base of your project it will update the packages.json to include node-java as a dependency.  It also adds the java directory and its contents to the ./node_modules/java directory.  This however is not a working copy.

This is attested to by the fact that if you cd to the node_moduels/java directory and try to run"

```npm test```

It will fail.

If however you run"

```
npm install
npm test
```

This does work.
