### ISSUE TITLE
classpath containing Chinese characters and there will be Java lang. NoClassDefFoundError

### ISSUE THREAD

**Issue by zhengxiwan** [joeferner/node-java#519]
os: window 10 x64
java: OpenJDK 64-Bit Server VM (Zulu 8.52.0.23-CA-win64) (build 25.282-b08, mixed mode)

eg:
```java
const jarPath="C:\\Users\\xxx\\Desktop\\中文\\data\\desktop-1.0.1.jar";
const jResponseResult = java.import("com.xxx.ResponseResult");
```
error:
```
var clazz = java.findClassSync(name); // TODO: change to Class.forName when classloader issue is resolved.                   ^

Error: Could not create class com.xxx.ResponseResult
java.lang.NoClassDefFoundError: com/xxx/ResponseResult
Caused by: java.lang.ClassNotFoundException: com.xxx.ResponseResult
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
```

**Comment by fanyuna** [comment]
I have the same problem. Have you solved it?
