### ISSUE TITLE
'Error: Module did not self-register.' with Worker Threads

### ISSUE THREAD

**Issue by davideutsch** [joeferner/node-java#533]
When I try to use the library in multiple threads (worker_threads), I get `Error: Module did not self-register.` exception. 
Within the main thread no problems arise, however as soon as a new worker is created this error is thrown.
### Environment
- Node version: 12.18.1
- Typescript: 3.6.4
### Full Stack Trace
```
Error: Module did not self-register: '\\?\C:\projectFolder\node_modules\java\build\Release\nodejavabridge_bindings.node' 
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\projectFolder\node_modules\java\lib\nodeJavaBridge.js:21:16)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Module._compile (C:\projectFolder\node_modules\source-map-support\source-map-support.js:547:25)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32) 
```

**Comment by tonioss22** [comment]
+1 i have the same error

**Comment by tonioss22** [comment]
I'm unsure if this would fix it, but it seems to be the same issue as a lot of other node modules, #https://github.com/nodejs/node/issues/21783#issuecomment-429637117

**Comment by tonioss22** [comment]
I've looked more into it this morning and it seems that making it context aware does work and fix the issue but it also causes the software to close on itself as soon as you use java without any error message. I have not been able to fix this issue yet.
