### ISSUE TITLE
node-java v0.12.2 fails with electron-rebuild (fatal error LNK1120)

### ISSUE THREAD

**Issue by DManstrator** [joeferner/node-java#541]
Hello.

I am tbh not sure whether this is a issue with electron-rebuild or node-java, I assume it's an issue here since building works for version `0.12.1` although the execution fails due to NODE_MODULE_VERSION mismatch (but that's another story I guess).

When I try to use `electron-rebuild -f -w java -v 12.2.2`, it fails since `electronbrowser\src\main\electron\node_modules\java\build\Release\nodejavabridge_bindings.node` does not exist. However in the `node_modules` in the output folder (`electronbrowser\target\generatedApp\resources\app\node_modules`), this (and more files) exist (see screenshots below).

I would be glad to get some help on this, spend a day trying to resolve it but without any success. When you need more information, please notify me.

#### Software
| software                                    | version |
|---------------------------------------------|---------|
| Visual Studio Community 2019                | 16.11.6 |
| Workload <br>`Desktop development with C++` | yes     |
| Python                                      | 3.10.0  |

#### Dependencies
| dependency       | version |
|------------------|---------|
| node             | 16.1.0  |
| electron         | 12.2.2  |
| electron-packager | 15.4.0 |
| electron-rebuild | 3.2.5   |
| node-java        | 0.12.2  |

### Execution:
```
electron-packager . %electron_application% --overwrite --out %out% --extra-resource=%extra_resource_viewer% --extra-resource=%extra_resource_app% --icon=%electron_icon% --prune && electron-rebuild -f -w java -v 12.2.2
```

### Logs / Stacktrace (partially in German)

```log
[INFO] --- frontend-maven-plugin:1.12.0:npm (npm package electron app) @ electronbrowser ---
[INFO] Running 'npm run package-electron' in C:\Users\[...]\electronbrowser\src\main\electron
[INFO]
[INFO] > Electron-Browser@1.0.0 package-electron
[INFO] > electron-packager . %electron_application% --overwrite --out %out% --extra-resource=%extra_resource_viewer% --extra-resource=%extra_resource_app% --icon=%electron_icon% --prune && npm run rebuild
[INFO]
[INFO] Packaging app for platform win32 x64 using electron v12.2.2
[INFO] Wrote new app to ..\..\..\target\generatedApp
[INFO]
[INFO] > Electron-Browser@1.0.0 rebuild
[INFO] > electron-rebuild -f -w java -v 12.2.2
[INFO]
[INFO] - Searching dependency tree
[INFO] Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm?glichen, m?ssen Sie den Schalter "-m" hinzuf?gen.
[INFO]   java.cpp
[INFO] C:\Users\myUserName\.electron-gyp\12.2.2\include\node\v8.h(1650,55): warning C4996: 'v8::Module::ResolveCallback': Use ResolveModuleCallback [C:\Users\[...]\electronbrowser\src\main\electron\node_modules\java\build\nodejavabridge_bindings.vcxproj]
[INFO]   javaObject.cpp
[INFO] C:\Users\myUserName\.electron-gyp\12.2.2\include\node\v8.h(1650,55): warning C4996: 'v8::Module::ResolveCallback': Use ResolveModuleCallback [C:\Users\[...]\electronbrowser\src\main\electron\node_modules\java\build\nodejavabridge_bindings.vcxproj]
[INFO]   javaScope.cpp
[INFO]   methodCallBaton.cpp
[INFO] C:\Users\myUserName\.electron-gyp\12.2.2\include\node\v8.h(1650,55): warning C4996: 'v8::Module::ResolveCallback': Use ResolveModuleCallback [C:\Users\[...]\electronbrowser\src\main\electron\node_modules\java\build\nodejavabridge_bindings.vcxproj]
[INFO]   nodeJavaBridge.cpp
[INFO] C:\Users\myUserName\.electron-gyp\12.2.2\include\node\v8.h(1650,55): warning C4996: 'v8::Module::ResolveCallback': Use ResolveModuleCallback [C:\Users\[...]\electronbrowser\src\main\electron\node_modules\java\build\nodejavabridge_bindings.vcxproj]
[INFO]   utils.cpp
[INFO] C:\Users\myUserName\.electron-gyp\12.2.2\include\node\v8.h(1650,55): warning C4996: 'v8::Module::ResolveCallback': Use ResolveModuleCallback [C:\Users\[...]\electronbrowser\src\main\electron\node_modules\java\build\nodejavabridge_bindings.vcxproj]
[INFO]   win_delay_load_hook.cc
[INFO]      Bibliothek "C:\Users\[...]\electronbrowser\src\main\electron\node_modules\java\build\Release\nodejavabridge_bindings.lib" und Objekt "C:\Users\[...]\electronbrowser\src\main\electron\node_modules\java\build\Release\nodejavabridge_bindings.exp" werden erstellt.
[INFO] utils.obj : error LNK2001: Nicht aufgel?stes externes Symbol ""__declspec(dllimport) public: class std::shared_ptr<class v8::BackingStore> __cdecl v8::ArrayBuffer::GetBackingStore(void)" (__imp_?GetBackingStore@ArrayBuffer@v8@@QEAA?AV?$shared_ptr@VBackingStore@v8@@@std@@XZ)". [C:\Users\[...]\electronbrowser\src\main\electron\node_modules\java\build\nodejavabridge_bindings.vcxproj]
[INFO] utils.obj : error LNK2001: Nicht aufgel?stes externes Symbol ""__declspec(dllimport) public: class std::shared_ptr<class v8::BackingStore> __cdecl v8::ArrayBuffer::GetBackingStore(void)" (__imp_?GetBackingStore@ArrayBuffer@v8@@QEAA?AV?$shared_ptr@VBackingStore@v8@@@std@@XZ)". [C:\Users\[...]\electronbrowser\src\main\electron\node_modules\java\build\nodejavabridge_bindings.vcxproj]Ã? Rebuild Failed
[INFO] C:\Users\[...]\electronbrowser\src\main\electron\node_modules\java\build\Release\nodejavabridge_bindings.node : fatal error LNK1120: 1 nicht aufgel?ste Externe [C:\Users\[...]\electronbrowser\src\main\electron\node_modules\java\build\nodejavabridge_bindings.vcxproj]
[INFO]
[INFO] An unhandled error occurred inside electron-rebuild
[INFO] node-gyp failed to rebuild 'C:\Users\[...]\electronbrowser\src\main\electron\node_modules\java'.
[INFO] For more information, rerun with the DEBUG environment variable set to "electron-rebuild".
[INFO]
[INFO] Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
[INFO]
[INFO]
[INFO]
[INFO] Error: node-gyp failed to rebuild 'C:\Users\[...]\electronbrowser\src\main\electron\node_modules\java'.
[INFO] For more information, rerun with the DEBUG environment variable set to "electron-rebuild".
[INFO]
[INFO] Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
[INFO]
[INFO]
[INFO]     at NodeGyp.rebuildModule (C:\Users\[...]\electronbrowser\src\main\electron\node_modules\electron-rebuild\lib\src\module-type\node-gyp.js:117:19)
[INFO]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[INFO]     at async ModuleRebuilder.rebuildNodeGypModule (C:\Users\[...]\electronbrowser\src\main\electron\node_modules\electron-rebuild\lib\src\module-rebuilder.js:94:9)
[INFO]     at async ModuleRebuilder.rebuild (C:\Users\[...]\electronbrowser\src\main\electron\node_modules\electron-rebuild\lib\src\module-rebuilder.js:124:14)
[INFO]     at async Rebuilder.rebuildModuleAt (C:\Users\[...]\electronbrowser\src\main\electron\node_modules\electron-rebuild\lib\src\rebuild.js:145:13)
[INFO]     at async Rebuilder.rebuild (C:\Users\[...]\electronbrowser\src\main\electron\node_modules\electron-rebuild\lib\src\rebuild.js:108:17)
[INFO]     at async C:\Users\[...]\electronbrowser\src\main\electron\node_modules\electron-rebuild\lib\src\cli.js:154:9
```

### Folder comparison

|                        source folder (`electronbrowser\src\main\electron\node_modules`)                        |                 ouput folder (`electronbrowser\target\generatedApp\resources\app\node_modules`)                |
|:--------------------------------------------------------------------------------------------------------------:|:--------------------------------------------------------------------------------------------------------------:|
| ![image](https://user-images.githubusercontent.com/7572614/141476918-c4d4575a-aded-4516-8dbc-81894160e012.png) | ![image](https://user-images.githubusercontent.com/7572614/141476717-2ea1f900-be74-492b-bf9d-d4481fcd5acc.png) |

**Comment by DoMyBestFor** [comment]
How did you solve this problem?

**Comment by DManstrator** [comment]
> How did you solve this problem?

I didn't find a solution for this problem as of now, I'm still hoping for an answer.

**Comment by jianchang69** [comment]
> 0.12.1

Hi,
Would you please give me the node-java v0.12.1 can rebuild in Electron project or Procedure ?
I can't success to rebuild node-java with electron...
So many thanks...

**Comment by DManstrator** [comment]
@jianchang69 You should use npm to get the dependencies. Just pin the version to `0.12.1` in your `package.json`.

**Comment by jianchang69** [comment]
> 

thank DManstrator,
I can rebuild v.0.12.1 and electron v.12.2.2. But hopefully still can rebuild with newest electron version ...
The electron latest version is v.17 with can't rebuild with node-java v.0.12.1..even electron v.14 rebuild fail.

**Comment by DManstrator** [comment]
Yeah, that's exactly the same issue I currently face hence why I opened this issue. I still need to find a new approach to this since this library seems unmaintained. In worst case, I have to re-implement everything in a different language. But for now, it's pretty low on my ToDo list.

**Comment by FlyingNoob** [comment]
The same problem

**Comment by ddrigass** [comment]
The same...

**Comment by jianchang69** [comment]
hi, ddrigass
we can rebuild node-java 0.12.2 with electron v18
thank a lot your information..
but when java code return byte array type to javascript, it happend error...><

I doubte here is problem:
Nan::MaybeLocal<v8::Value> ab = Nan::Get(v8Buf, Nan::New<v8::String>("cause").ToLocalChecked());
Do you have any idea? 
the "cause" this word should be modified to ?

**Comment by xinnianyoulin** [comment]
> For me solved here: lygstate/node-java #532 Thank you!

Thanks, it works at electron 24.1.2
