### ISSUE TITLE
jni.h file not found on Ox12.2 Montery

### ISSUE THREAD

**Issue by HarveyLee1228** [joeferner/node-java#552]
CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
In file included from ../src/java.cpp:1:
../src/java.h:7:10: fatal error: 'jni.h' file not found
#include <jni.h>
         ^~~~~~~
1 error generated.
make: *** [Release/obj.target/nodejavabridge_bindings/src/java.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 21.3.0

I'm sure I hava set the JAVA_HOME:

➜  ~ echo $JAVA_HOME/
/Library/Java/JavaVirtualMachines/jdk1.8.0_331.jdk/Contents/Home/

Anyone can help? Thanks

**Comment by HarveyLee1228** [comment]
problem solved. It's about sudo yarn install command. I reinstall the yarn using "sudo -s   npm install -g yarn", then run yarn install ,it works.
